Repository bratislava/konto.bratislava.sk, pull requests merged in 2023-11, with the labels that each got.

#560 Make consistent and use standardized RJSF widget names
  next/components/forms/ThemedForm.tsx
  next/components/forms/steps/Summary/SummaryForm.tsx
  next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
  next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/FileUploadWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaWidgetRJSF.tsx
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/kalkulacky.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/stavbyBase.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step1.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step7.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/vyplnitKrokRadio.ts
  next/schema-generator/definitions/shared/investicne.ts
  next/schema-generator/definitions/showcase.ts
  next/schema-generator/generator/functions.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: needs review :pray:

#559 Refactor sections my applications
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsHeader.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
Labels: pr: fix & ship :ship:

#561 Form signature
  next/components/forms/FormPageWrapper.tsx
  next/components/forms/signer/signerExamplePayload.ts
  next/components/forms/signer/signerTypes.ts
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/signer/useFormSigner.ts
  next/components/forms/signer/useFormSignerLoader.tsx
  next/components/forms/steps/Summary/FormSummary.tsx
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/components/forms/steps/Summary/SummaryFormSignature.tsx
  next/components/forms/steps/Summary/useFormSummary.tsx
  next/components/forms/useFormSend.tsx
  next/components/forms/useFormState.tsx
  next/frontend/types/initialFormData.ts
  next/frontend/utils/formSummary.ts
  next/package.json
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#565 Add support for size for all fields (not only inputs), make consisten…
  next/components/forms/segments/CorrespondenceAddressForm/CorrespondenceAddressForm.tsx
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/FieldBase.ts
  next/components/forms/widget-components/FieldWrapper.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/FileUploadWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/stavbyBase.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step1.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/shared/investicne.ts
  next/schema-generator/definitions/showcase.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: fix & ship :ship:

#557 [#10] add new MunicipalService tile zavazne
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/frontend/api/constants.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#558 [#539] fix styling concept_delete
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
Labels: pr: fix & ship :ship:

#562 [#522] styling Registration modal
  next/components/forms/segments/RegistrationModal/RegistrationModal.tsx
Labels: pr: fix & ship :ship:

#564 [bratislava/private-konto.bratislava.sk#31] translations
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#563 Make the sections header scroll horizontaly
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
Labels: pr: fix & ship :ship:

#572 Dane improvements v2
  next/components/forms/info-components/FieldFooter.tsx
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/FieldHelptext.tsx
  next/components/forms/steps/Summary/SummaryForm.tsx
  next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/FieldBase.ts
  next/components/forms/widget-components/FieldWrapper.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/SelectField/SelectFieldNew/ComboBoxNew.tsx
  next/components/forms/widget-components/SelectField/SelectFieldNew/ListBoxItem.tsx
  next/components/forms/widget-components/SelectField/SelectFieldNew/SelectFieldNew.tsx
  next/components/forms/widget-components/SelectField/SelectFieldNew/SelectMultiNew.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-wrappers/BAArrayFieldItemTemplate.tsx
  next/components/forms/widget-wrappers/BAArrayFieldTemplate.tsx
  next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
  next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/FileUploadWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/WidgetWrapper.tsx
  next/components/forms/widget-wrappers/useWidgetSpacingContext.tsx
  next/components/styleguide/showcases/FieldHeaderShowCase.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
  next/components/styleguide/showcases/SelectFieldNewShowCase.tsx
  next/components/styleguide/showcases/SelectMultiNewShowCase.tsx
  next/frontend/utils/formArray.ts
  next/public/locales/sk/account.json
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step7.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/vyplnitKrokRadio.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: needs review :pray:

#567 [bratislava/private-konto.bratislava.sk#21] modals back + main button styling
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/widget-components/Modals/MessageModal.tsx
Labels: pr: fix & ship :ship:

#578 [#539] change translations during concept delete
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
Labels: pr: fix & ship :ship:

#579 [bratislava/private-konto.bratislava.sk#31] typo fix
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#581 Dane improvements v3
  next/components/forms/ThemedForm.tsx
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/FormLightboxModal.tsx
  next/components/forms/info-components/FormMarkdown.tsx
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/simple-components/LightboxModal.tsx
  next/components/forms/steps/Summary/SummaryForm.tsx
  next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
  next/components/forms/widget-wrappers/CheckboxGroupWidgetRJSF.tsx
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
  next/frontend/utils/form.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/kalkulacky.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/schema-generator/generator/functions.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: needs review :pray:

#580 [bratislava/private-konto.bratislava.sk#10] add municipal service investing intent tile
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/frontend/api/constants.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#586 Dane improvements v4
  next/components/forms/FormPage.tsx
  next/components/forms/info-components/FormMarkdown.tsx
  next/components/forms/types/Steps.ts
  next/components/forms/widget-wrappers/BAArrayFieldTemplate.tsx
  next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
  next/frontend/utils/formState.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/stavbyBase.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step7.ts
  next/schema-generator/generator/functions.ts
Labels: pr: needs review :pray:

#588 [bratislava/private-konto.bratislava.sk#41] add alert in StatusBar
  next/components/forms/info-components/StatusBar.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/public/locales/sk/common.json
Labels: pr: fix & ship :ship:

#577 Add applications count to header
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
  next/pages/moje-ziadosti/index.tsx
Labels: pr: fix & ship :ship:

#584 [bratislava/private-konto.bratislava.sk#36] MyApplicationsCard date condition
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/frontend/hooks/useFormStateComponents.tsx
Labels: pr: fix & ship :ship:

#574 #450 my applications fixes reupload
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/BottomSheetMenu/BottomSheetMenuModal.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/BottomSheetMenu/BottomSheetMenuRow.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationCardsPlaceholder.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/components/forms/simple-components/FormHeader.tsx
  next/components/forms/simple-components/MenuDropdown/MenuDropdown.tsx
  next/components/forms/simple-components/MenuDropdown/MenuTrigger.tsx
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#594 Dane improvements v5
  next/.eslintrc.js
  next/components/forms/info-components/FormMarkdown.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/segments/PropertyTaxCalculator/PropertyTaxCalculator.tsx
  next/components/forms/simple-components/Pagination/usePagination.ts
  next/components/forms/useFormSend.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/environment.ts
  next/frontend/utils/form.ts
  next/frontend/utils/formSend.ts
  next/pages/aktivacia-konta.tsx
  next/pages/api/robots.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/kalkulacky.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/schema-generator/definitions/shared/investicne.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: needs review :pray:

#596 Calculator fix
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
Labels: pr: needs review :pray:

#599 [bratislava/private-konto.bratislava.sk#36] change icon when form is in READY_FOR_PROCESSING
  next/frontend/hooks/useFormStateComponents.tsx
Labels: pr: fix & ship :ship:

#598 Form changes
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
Labels: pr: needs review :pray:

#591 Add zip mime
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
Labels: pr: needs review :pray:

#597 Use url for pagination in my applications
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
Labels: pr: fix & ship :ship:

#601 [#600] Trim text at the end of line
  next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
  next/components/forms/widget-components/SelectField/Dropdown.tsx
  next/components/forms/widget-components/SelectField/DropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/SelectField/SelectFieldBox.tsx
  next/components/forms/widget-wrappers/SelectWidgetRJSF.tsx
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: fix & ship :ship:

#593 [#539] change concept delete snackbar translations
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#587 #30 form launch landing page
  next/assets/images/construction-sci-fi.png
  next/assets/images/corporate-identity.png
  next/assets/images/kupaliska.png
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#603 [#595] fix verify identity button in header
  next/components/forms/simple-components/IdentityVerificationStatus.tsx
Labels: pr: needs review :pray:

#626 [#619] add missing captcha - identity verification
  next/frontend/dtos/generalApiDto.ts
  next/pages/overenie-identity.tsx
Labels: pr: needs review :pray:

#629 [#549] Form title + created/update date from GINIS
  next/clients/openapi-forms/api.ts
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetails.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
  next/frontend/hooks/useFormStateComponents.tsx
  next/frontend/utils/general.ts
  next/schema-generator/definitions/shared/investicne.ts
Labels: pr: needs review :pray:

#615 [bratislava/private-konto.bratislava.sk#39] add distinction isLegalEntity when showing MunicipalServices
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/frontend/constants/constants.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#613 [#612] user name missing
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
Labels: pr: fix & ship :ship:

#611 [#590] move hardcoded text to translations
  next/components/forms/useFormRedirects.tsx
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#617 Allow user to change email
  next/components/forms/segments/EmailChangeForm/EmailChangeForm.tsx
  next/components/forms/segments/UserProfile/UserProfileDetail.tsx
  next/components/forms/segments/UserProfile/UserProfileDetailEdit.tsx
  next/components/forms/segments/UserProfile/UserProfileDetailView.tsx
  next/components/forms/segments/UserProfile/UserProfileView.tsx
  next/pages/zmena-emailu.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#553 Update node to 20, then next update and removal of various packages
  .github/workflows/pull.yml
  next/Dockerfile
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/schema.json
  next/clients/openapi-forms/api.ts
  next/clients/openapi-forms/base.ts
  next/components/forms/segments/AccountSectionHeader/TaxFeeSectionHeader.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
  next/components/forms/segments/UserProfile/UserProfilePhoto.tsx
  next/components/forms/simple-components/Button.tsx
  next/components/forms/simple-components/Pagination/usePagination.ts
  next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
  next/components/forms/widget-components/SelectField/SelectFieldBox.tsx
  next/components/forms/widget-components/Upload/UploadFileCard.tsx
  next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
  next/next.config.js
  next/package.json
  next/pages/mestske-sluzby/[slug]/index.tsx
  next/pages/overenie-identity.tsx
  next/patches/README.md
  next/schema-generator/README.md
  next/schema-generator/generator/functions.ts
  next/yarn.lock
Labels: pr: infrastructure, pr: fix & ship :ship:

#630 [#627] change logging library
  next/components/forms/segments/AccountErrorAlert/AccountErrorAlert.tsx
  next/frontend/utils/logger.ts
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:

#642 Add AliasExistsException error message
  next/pages/zmena-emailu.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#647 Dane improvements v9
  next/components/forms/FormPage.tsx
  next/components/forms/info-components/FormLightboxModal.module.css
  next/components/forms/info-components/FormLightboxModal.tsx
  next/components/forms/simple-components/LightboxModal.tsx
  next/components/forms/steps/Summary/SummaryArrayTemplateRJSF.tsx
  next/components/forms/steps/Summary/SummaryForm.tsx
  next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
  next/package.json
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/stavbyBase.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/yarn.lock
Labels: pr: needs review :pray:
