Repository bratislava/konto.bratislava.sk, pull requests merged in 2024-08, with the labels that each got.

#1230 Example dev forms
  forms-shared/src/example-forms/exampleForms.ts
  forms-shared/src/example-forms/getExampleFormPairs.ts
Labels: pr: needs review :pray:

#1260 Release Žiadost o nájomný byt V2
  forms-shared/src/schemas/ziadostONajomnyByt.ts
Labels: pr: needs review :pray:

#1258 Small pipeline cleanup
  .github/workflows/build-conditions-konto.yml
  .github/workflows/cluster-deploy-conditions-konto.yml
  .github/workflows/deploy.yml
  .github/workflows/validate-nest-prisma-konto.yml
Labels: pr: needs review :pray:

#1264 Release Žiadosť o nájomny byt V3
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/slovensko-sk/generateXml.ts
  forms-shared/src/slovensko-sk/xmlBuilder.ts
  forms-shared/tests/definitions/formDefinitions.ts
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  nest-forms-backend/src/convert/convert.controller.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/convert/dtos/form.dto.ts
  nest-forms-backend/src/convert/errors/convert.errors.dto.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
  next/clients/openapi-forms/api.ts
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/generateOpenApiClient.ts
Labels: pr: needs review :pray:

#1160 add link to product specification
  README.md
Labels: pr: fix & ship :ship:

#1212 added delete notification to scanner when files are deleted
  nest-forms-backend/src/files/files.errors.enum.ts
  nest-forms-backend/src/files/files.helper.ts
  nest-forms-backend/src/files/files.service.ts
Labels: pr: needs review :pray:

#1274 fixed typo in scanner name
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:, issue: bug

#1287 Updated readme
  README.md
  nest-forms-backend/README.md
Labels: pr: fix & ship :ship:

#1270 Ignore iframe-resizer-child.js
  next/.gitignore
Labels: pr: fix & ship :ship:

#1269 Create form shared sandbox
  forms-shared/package.json
  forms-shared/scripts/sandbox.ts
Labels: pr: fix & ship :ship:

#1268 Fix form context
  next/__tests__/form-file-upload.test.tsx
  next/components/forms/FormPageWrapper.tsx
  next/components/forms/FormProviders.tsx
  next/components/forms/PdfSummaryPage.tsx
  next/components/forms/useFormContext.tsx
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/dev/[slug].ts
Labels: pr: fix & ship :ship:

#1296 Refactor input formats + add Slovak phone number format
  forms-shared/src/form-utils/ajvFormats.ts
  forms-shared/src/generator/functions.ts
  forms-shared/src/generator/helpers.ts
  forms-shared/src/generator/uiOptionsTypes.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozALikvidaciaOdpadu.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/osoby.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/stavbyBase.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step3.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step4.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step5.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step6.ts
  forms-shared/src/schemas/sekcia-uzemneho-rozvoja/surSchemas.ts
  forms-shared/src/schemas/shared/fields.ts
  forms-shared/src/schemas/ziadostONajomnyByt.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/form-utils/defaultFormState.ts
  forms-shared/tests/form-utils/fileUtils.ts
  forms-shared/tests/form-utils/omitExtraData.ts
  forms-shared/tests/summary-json/getSummaryDisplayValue.tsx
  forms-shared/tests/summary-renderer/validateSummary.ts
  next/components/forms/widget-wrappers/InputWidgetRJSF.tsx
Labels: pr: needs review :pray:

#1300 added dependabot for nest-clamav-scanner
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#1314 Oznam: Čiastočný výpadok platobnej brány
  next/public/locales/sk/common.json
Labels: pr: fix & ship :ship:

#1316 Fix flaky cypress registration test v2
  tests/cypress/e2e/registration/registration.cy.ts
Labels: pr: needs review :pray:

#1317 Najomne byvanie euro icon
  forms-shared/src/generator/uiOptionsTypes.ts
  forms-shared/src/schemas/ziadostONajomnyByt.ts
  next/assets/ui-icons/euro.svg
  next/assets/ui-icons/index.ts
  next/components/forms/widget-components/InputField/InputField.tsx
Labels: pr: needs review :pray:

#1315 Use camel case keys for selects/radio groups in Najomne byvanie
  forms-shared/src/example-forms/examples/ziadostONajomnyBytExample.ts
  forms-shared/src/schemas/ziadostONajomnyByt.ts
Labels: pr: needs review :pray:

#1318 Najomne byvanie adjustments v3
  forms-shared/src/example-forms/examples/ziadostONajomnyBytExample.ts
  forms-shared/src/generator/functions.ts
  forms-shared/src/schemas/ziadostONajomnyByt.ts
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najomny-byt-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najomny-byt-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-7-snap.png
Labels: pr: needs review :pray:

#1333 fix: use fixed private key format
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
Labels: pr: fix & ship :ship:

#1334 fix: correct nases secrets format
  nest-forms-backend/kubernetes/base/secrets/nases.secret.staging.yml
Labels: pr: fix & ship :ship:

#1335 Najomne byvanie adjustments v6
  forms-shared/src/example-forms/examples/ziadostONajomnyBytExample.ts
  forms-shared/src/schemas/ziadostONajomnyByt.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najomny-byt-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/string-templates/__snapshots__/renderTemplate.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najomny-byt-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najomny-byt-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najomny-byt-example-summary-pdf-should-match-snapshot-1-snap.png
  next/components/forms/widget-components/DateTimePicker/Calendar/CalendarGrid.tsx
Labels: pr: needs review :pray:
