Repository bratislava/konto.bratislava.sk, pull requests merged in 2024-10, with the labels that each got.

#1482 Allowing dependabot to run pipelines
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#1483 updated permissions on pipelines to make it run for depenadbot
  .github/dependabot.yml
  .github/workflows/validate-and-build.yml
Labels: pr: fix & ship :ship:

#1477 fix: add VlastnikNehnutelnosti to other members mapping
  forms-shared/src/example-forms/examples/ziadostONajomBytuExample.ts
  forms-shared/src/sharepoint/mappings/ziadostONajomBytu.ts
  forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap
Labels: pr: fix & ship :ship:

#1458 feat: backend preparation for sending email forms
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/summary-email/renderSummaryEmail.tsx
  nest-forms-backend/prisma/migrations/20240926105218_add_email_send_error/migration.sql
  nest-forms-backend/prisma/schema.prisma
  nest-forms-backend/src/common/utils/helpers.ts
  nest-forms-backend/src/forms/forms.helper.spec.ts
  nest-forms-backend/src/forms/forms.helper.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.module.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.spec.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/nases/nases.controller.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
  nest-forms-backend/src/utils/global-dtos/mailgun.dto.ts
  nest-forms-backend/src/utils/global-services/mailgun/mailgun.constants.ts
  nest-forms-backend/src/utils/subservices/dtos/email-forms.errors.enum.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1508 Staging pipeline bugfix for nest-tax-backend
  .github/workflows/cluster-deploy-conditions-konto.yml
  README.md
Labels: pr: infrastructure, pr: fix & ship :ship:

#1509 Docker.com login for pipelines
  .github/workflows/deploy.yml
  .github/workflows/validate-and-build.yml
Labels: pr: infrastructure, pr: fix & ship :ship:

#1487 feat: webhook forms
  forms-shared/src/definitions/formDefinitionTypes.ts
  nest-forms-backend/prisma/migrations/20241007081334_add_webhook_send_error/migration.sql
  nest-forms-backend/prisma/schema.prisma
  nest-forms-backend/src/nases-consumer/nases-consumer.module.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.spec.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/webhook.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/dtos/email-forms.errors.enum.ts
  nest-forms-backend/src/nases-consumer/subservices/dtos/webhook.dto.ts
  nest-forms-backend/src/nases-consumer/subservices/dtos/webhook.errors.enum.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/nases-consumer/subservices/webhook.subservice.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1530 Change texts in najomne byvanie v2
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najom-bytu-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najom-bytu-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-7-snap.png
Labels: pr: fix & ship :ship:

#1398 chore: update eslint in nest-forms-backend
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/convert/utils-services/createXmlTemplate.ts
  nest-forms-backend/src/files/files.helper.ts
  nest-forms-backend/src/tax/tax.module.ts
  nest-forms-backend/src/utils/middlewares/logger.service.ts
Labels: pr: fix & ship :ship:

#1534 Chore: Remove unused packages from nest-forms-backend
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
Labels: pr: fix & ship :ship:

#1544 OLO forms prelease adjustments FE
  next/.env.bratiska-cli-build.prod
  next/components/forms/useFormContext.tsx
  next/components/forms/useFormSend.tsx
Labels: pr: fix & ship :ship:

#1545 OLO forms render email url support
  forms-shared/src/summary-email/SummaryEmail.tsx
  forms-shared/src/summary-email/renderSummaryEmail.tsx
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-komunitne-zahrady-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-komunitne-zahrady-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-podnety-a-pochvaly-obcanov-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-podnety-a-pochvaly-obcanov-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-predzahradky-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-predzahradky-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/renderSummaryEmail.ts
Labels: pr: fix & ship :ship:

#1546 rename allowSendingByUnverifiedUsers to allowSendingUnauthenticatedUsers
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/forms/forms.helper.spec.ts
  nest-forms-backend/src/forms/forms.helper.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
  next/components/forms/useFormContext.tsx
Labels: pr: fix & ship :ship:

#1551 Temporarily increase PDF timeout
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
  forms-shared/tests/summary-pdf/renderSummaryPdf.ts
  forms-shared/tests/tax-form/taxForm.ts
Labels: pr: fix & ship :ship:

#1548 Send confirmation pdf as attachment to user in OLO forms
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/utils/global-services/mailgun/mailgun.service.ts
Labels: pr: fix & ship :ship:

#1568 Special modal positioning when the page is in iframe
  next/components/forms/FormPage.tsx
  next/components/forms/FormPageWrapper.tsx
  next/components/forms/IframeResizerChild.tsx
  next/components/forms/simple-components/ModalV2.tsx
Labels: pr: fix & ship :ship:

#1569 Allow embedding of forms on non-dev URLs
  next/frontend/utils/embeddedFormsAllowedOrigins.ts
  next/frontend/utils/embeddedFormsHelpers.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/[slug]/index.tsx
  next/pages/mestske-sluzby/dev/[slug].ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1570 Fix rendering of emails in Outlook
  forms-shared/src/summary-email/SummaryEmail.tsx
Labels: pr: fix & ship :ship:

#1572 Bump iframe resizer
  next/components/forms/IframeResizerChild.tsx
  next/package-lock.json
  next/package.json
Labels: pr: fix & ship :ship:

#1571 Conditionally display send with eID button
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/components/forms/useFormContext.tsx
  next/components/forms/useFormSend.tsx
Labels: pr: fix & ship :ship:

#1552 Filter GINIS details in form detail page
  next/frontend/utils/ginis.ts
Labels: pr: fix & ship :ship:

#1573 fix: allow file upload for all forms, use slug instead of pospID
  nest-forms-backend/src/convert-pdf/convert-pdf.service.ts
  nest-forms-backend/src/files/__tests__/files.controller.spec.ts
  nest-forms-backend/src/files/__tests__/files.helper.spec.ts
  nest-forms-backend/src/files/__tests__/files.service.spec.ts
  nest-forms-backend/src/files/files.dto.ts
  nest-forms-backend/src/files/files.helper.ts
  nest-forms-backend/src/files/files.service.ts
Labels: pr: fix & ship :ship:

#1575 Fix URL generation in summary email
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
Labels: pr: needs review :pray:

#1577 Add IFRAME_RESIZER_PUBLIC_PATH with version to prevent browser caching
  next/.gitignore
  next/components/forms/IframeResizerChild.tsx
  next/environment.ts
  next/next.config.js
Labels: pr: fix & ship :ship:

#1579 Fix EmailFormsSubservice test
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
Labels: pr: fix & ship :ship:

#1578 OLO make all emails required
  forms-shared/src/example-forms/examples/oloDocistenieStanovistaZbernychNadobExample.ts
  forms-shared/src/example-forms/examples/oloKoloTaxiExample.ts
  forms-shared/src/example-forms/examples/oloMimoriadnyOdvozAZhodnotenieOdpaduExample.ts
  forms-shared/src/example-forms/examples/oloOloTaxiExample.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-docistenie-stanovista-zbernych-nadob-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-docistenie-stanovista-zbernych-nadob-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-olo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-olo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-docistenie-stanovista-zbernych-nadob-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-kolo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-olo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
Labels: pr: fix & ship :ship:

#1576 use olo success mail for user
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/utils/global-services/mailgun/mailgun.constants.ts
Labels: pr: fix & ship :ship:

#1580 Clean whitespace from base64 form data before sending
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
Labels: pr: fix & ship :ship:

#1589 Revert "Revert "Enable NEXT_PUBLIC_FEATURE_TOGGLE_EID_TAX_WITHOUT_BETA_FLAG in production""
  next/.env.bratiska-cli-build.prod
Labels: pr: fix & ship :ship:

#1609 fixed wrong folder on validate nest-tax-backend
  .github/workflows/validate-and-build.yml
Labels: pr: fix & ship :ship:

#1611 OLO extract email and name from user data
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  next/components/forms/serializableFormDefinition.ts
  next/components/forms/useFormContext.tsx
  next/pages/forms-playground.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/dev/[slug].ts
Labels: pr: fix & ship :ship:

#1613 Require unique field properties schema generator
  forms-shared/src/generator/functions.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/osoby.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step4.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#1616 Revert "OLO extract email and name from user data"
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  next/components/forms/serializableFormDefinition.ts
  next/components/forms/useFormContext.tsx
  next/pages/forms-playground.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/dev/[slug].ts
Labels: pr: needs review :pray:

#1602 Remove unused packages in nest-tax-backend
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  nest-tax-backend/src/app.module.ts
  nest-tax-backend/src/utils/subservices/mailer.ts
Labels: pr: fix & ship :ship:

#1617 Olo extract email name V2
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
  next/components/forms/serializableFormDefinition.ts
  next/components/forms/useFormContext.tsx
  next/pages/forms-playground.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/dev/[slug].ts
Labels: pr: fix & ship :ship:

#1625 Add zakazka email
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#1623 Change access token policy when sending form
  next/components/forms/useFormSend.tsx
Labels: pr: fix & ship :ship:

#1626 Fix message subject olo forms
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
Labels: pr: fix & ship :ship:

#1628 Fix: install axios in tax backend
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
Labels: pr: fix & ship :ship:

#1591 TSB forms v1
  forms-shared/scripts/createAiPrompt.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/tsb/objednavkaVytycenie.ts
  forms-shared/src/schemas/tsb/objednavkaZakresuSieti.ts
  forms-shared/src/schemas/tsb/umiestnenieZariadenia.ts
  forms-shared/src/schemas/tsb/ziadostOStanoviskoPD.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#1630 Implement thank you page for embedded forms
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#1633 Olo forms schema adjustments
  forms-shared/src/example-forms/examples/oloEnergetickeZhodnotenieOdpaduVZevoExample.ts
  forms-shared/src/example-forms/examples/oloOloTaxiExample.ts
  forms-shared/src/generator/helpers.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/helpers.ts
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-olo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-olo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-kolo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-olo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-5-snap.png
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
Labels: pr: fix & ship :ship:

#1627 Send formId & fileUrls to webhooks
  forms-shared/src/summary-email/SummaryEmail.tsx
  forms-shared/src/summary-email/renderSummaryEmail.tsx
  forms-shared/tests/summary-email/renderSummaryEmail.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/webhook.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/dtos/webhook.dto.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/nases-consumer/subservices/webhook.subservice.ts
  nest-forms-backend/src/utils/__test__/files.spec.ts
  nest-forms-backend/src/utils/files.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1636 Olo forms fix email path
  forms-shared/src/example-forms/examples/oloKoloTaxiExample.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
Labels: pr: fix & ship :ship:

#1635 Log data of xml conversion on errors
  nest-forms-backend/src/convert/convert.controller.ts
Labels: pr: fix & ship :ship:

#1637 Create screenshotTestTimeout const and add it to renderSummaryEmail
  forms-shared/test-utils/consts.ts
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
  forms-shared/tests/summary-email/renderSummaryEmail.ts
  forms-shared/tests/summary-pdf/renderSummaryPdf.ts
  forms-shared/tests/tax-form/taxForm.ts
Labels: pr: needs review :pray:

#1639 Change "Súhlasy" in OLO forms and update snapshots
  forms-shared/src/example-forms/examples/oloDocistenieStanovistaZbernychNadobExample.ts
  forms-shared/src/example-forms/examples/oloEnergetickeZhodnotenieOdpaduVZevoExample.ts
  forms-shared/src/example-forms/examples/oloKoloTaxiExample.ts
  forms-shared/src/example-forms/examples/oloMimoriadnyOdvozAZhodnotenieOdpaduExample.ts
  forms-shared/src/example-forms/examples/oloOdvozObjemnehoOdpaduValnikomExample.ts
  forms-shared/src/example-forms/examples/oloOdvozOdpaduVelkokapacitnymAleboLisovacimKontajneromExample.ts
  forms-shared/src/example-forms/examples/oloOloTaxiExample.ts
  forms-shared/src/example-forms/examples/oloTriedenyZberPapieraPlastovASklaPrePravnickeOsobyExample.ts
  forms-shared/src/example-forms/examples/oloTriedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnostiExample.ts
  forms-shared/src/example-forms/examples/oloUzatvorenieZmluvyONakladaniSOdpadomExample.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-docistenie-stanovista-zbernych-nadob-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-docistenie-stanovista-zbernych-nadob-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-kolo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-mimoriadny-odvoz-a-zhodnotenie-odpadu-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-mimoriadny-odvoz-a-zhodnotenie-odpadu-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-odvoz-objemneho-odpadu-valnikom-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-odvoz-objemneho-odpadu-valnikom-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-odvoz-odpadu-velkokapacitnym-alebo-lisovacim-kontajnerom-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-odvoz-odpadu-velkokapacitnym-alebo-lisovacim-kontajnerom-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-olo-taxi-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-olo-taxi-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-docistenie-stanovista-zbernych-nadob-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-docistenie-stanovista-zbernych-nadob-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-kolo-taxi-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-mimoriadny-odvoz-a-zhodnotenie-odpadu-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-odvoz-objemneho-odpadu-valnikom-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-odvoz-odpadu-velkokapacitnym-alebo-lisovacim-kontajnerom-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-olo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-5-snap.png
Labels: pr: fix & ship :ship:

#1638 move to github runner
  .github/workflows/validate-forms-shared-konto.yml
Labels: pr: fix & ship :ship:
