Repository bratislava/konto.bratislava.sk, pull requests merged in 2024-09, with the labels that each got.

#1339 New slovensko sk forms xml import v2
  forms-shared/src/slovensko-sk/extractJson.ts
  forms-shared/tests/slovensko-sk/extractJson.ts
  nest-forms-backend/src/convert/convert.controller.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/convert/dtos/form.dto.ts
  nest-forms-backend/src/convert/errors/convert.errors.dto.ts
  nest-forms-backend/src/convert/errors/convert.errors.enum.ts
  next/clients/openapi-forms/.openapi-generator/VERSION
  next/clients/openapi-forms/api.ts
  next/frontend/hooks/useFormExportImport.tsx
Labels: pr: needs review :pray:

#1342 Bump "Žiadosť o nájomný byt" pospVersion
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
Labels: pr: needs review :pray:

#1341 Form landing pages in Strapi
  strapi/schema.graphql
  strapi/src/api/form/content-types/form/schema.json
  strapi/src/api/form/controllers/form.ts
  strapi/src/api/form/routes/form.ts
  strapi/src/api/form/services/form.ts
  strapi/src/components/blocks/form-landing-page-form-cta.json
  strapi/src/components/blocks/form-landing-page-link-cta.json
  strapi/src/components/blocks/form-landing-page.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1171 Feat/sharepoint forms
  .vscode/settings.json
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/definitions/sharepointTypes.ts
  forms-shared/src/example-forms/examples/ziadostONajomnyBytExample.ts
  forms-shared/src/example-forms/types.ts
  forms-shared/src/form-utils/omitExtraData.ts
  forms-shared/src/sharepoint/getValuesForSharepoint.ts
  forms-shared/src/sharepoint/mappings/ziadostONajomnyByt.ts
  forms-shared/src/sharepoint/types.ts
  forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap
  forms-shared/tests/sharepoint/getValuesForSharepoint.ts
  nest-forms-backend/kubernetes/base/deployment.yml
  nest-forms-backend/kubernetes/base/secrets/sharepoint.secret.dev.yml
  nest-forms-backend/kubernetes/base/secrets/sharepoint.secret.prod.yml
  nest-forms-backend/kubernetes/base/secrets/sharepoint.secret.staging.yml
  nest-forms-backend/kubernetes/base/secrets/sharepoint.yml
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/prisma/migrations/20240709085336_add_sharepoint_states/migration.sql
  nest-forms-backend/prisma/schema.prisma
  nest-forms-backend/src/app.module.ts
  nest-forms-backend/src/ginis/ginis.module.ts
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
  nest-forms-backend/src/ginis/subservices/ginis.helper.spec.ts
  nest-forms-backend/src/ginis/subservices/ginis.helper.ts
  nest-forms-backend/src/utils/subservices/__test__/sharepoint.subservice.spec.ts
  nest-forms-backend/src/utils/subservices/dtos/sharepoint.errors.enum.ts
  nest-forms-backend/src/utils/subservices/sharepoint.subservice.ts
Labels: pr: fix & ship :ship:

#1344 Remove xmlns:xsi from BaseFormXml in extractJson
  forms-shared/src/slovensko-sk/extractJson.ts
Labels: pr: needs review :pray:

#1354 fix: remove quotes from sharepoint k8 envs
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
Labels: pr: fix & ship :ship:

#1355 Make landingPage property optional
  strapi/schema.graphql
  strapi/src/api/form/content-types/form/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#1359 Remove LegacyObjectFieldUiOptions
  next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
Labels: pr: fix & ship :ship:

#1360 Create AI prompt utility
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/scripts/createAiPrompt.ts
Labels: pr: needs review :pray:

#1362 Feat/one to many in one field
  forms-shared/src/example-forms/examples/ziadostONajomnyBytExample.ts
  forms-shared/src/sharepoint/getValuesForSharepoint.ts
  forms-shared/src/sharepoint/mappings/ziadostONajomnyByt.ts
  forms-shared/src/sharepoint/types.ts
  forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap
  forms-shared/tests/sharepoint/getValuesForSharepoint.ts
  nest-forms-backend/src/utils/subservices/__test__/sharepoint.subservice.spec.ts
  nest-forms-backend/src/utils/subservices/sharepoint.subservice.ts
Labels: pr: fix & ship :ship:

#1361 Create empty OLO forms
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/src/schemas/olo/zevoMechanickaVykladkaAZhodnotenieOdpaduPodlaIntegrovanehoPovlenia.ts
  forms-shared/src/schemas/olo/zevoPodrvenieAZhodnotenieOdpaduVysypanimDoZasobnika.ts
  forms-shared/src/schemas/olo/zevoRucnaVykladkaAZhodnotenieOdpaduPodlaIntegrovanehoPovlenia.ts
  forms-shared/src/schemas/olo/zevoUzatvorenieZmluvyONakladaniSOdpadom.ts
Labels: pr: fix & ship :ship:

#1288 Move clamav to konto
  .github/workflows/cluster-deploy-conditions-konto.yml
  .github/workflows/deploy.yml
  clamav/Dockerfile
  clamav/README.md
  clamav/conf/clamd.conf
  clamav/conf/freshclam.conf
  clamav/health.sh
  clamav/kubernetes/base/.env
  clamav/kubernetes/base/configuration.yml
  clamav/kubernetes/base/deployment.yml
  clamav/kubernetes/base/kustomization.yml
  clamav/kubernetes/base/service-clamav.yml
  clamav/kubernetes/envs/Dev/.env
  clamav/kubernetes/envs/Dev/config.json
  clamav/kubernetes/envs/Dev/kustomization.yml
  clamav/kubernetes/envs/Prod/.env
  clamav/kubernetes/envs/Prod/config.json
  clamav/kubernetes/envs/Prod/kustomization.yml
  clamav/kubernetes/envs/Staging/.env
  clamav/kubernetes/envs/Staging/config.json
  clamav/kubernetes/envs/Staging/kustomization.yml
  clamav/package.json
  clamav/readiness.sh
  clamav/setupconfig.py
  clamav/start.py
  clamav/virustest
Labels: pr: fix & ship :ship:

#1374 feat: add a new sharepoint main table
  forms-shared/src/example-forms/examples/ziadostONajomnyBytExample.ts
  forms-shared/src/sharepoint/mappings/ziadostONajomnyByt.ts
  forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap
Labels: pr: fix & ship :ship:

#1380 Create migration for rename "Žiadosť o nájomný byt"
  nest-forms-backend/prisma/migrations/20240910140337_update_form_definition_slug_najomny_byt/migration.sql
Labels: pr: needs review :pray:

#1381 Najomne bývanie adjustments v8
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najom-bytu-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najom-bytu-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-7-snap.png
Labels: pr: needs review :pray:

#1384 Change Ginis assignee, allow ginis org name without person
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/ginis/ginis.service.ts
Labels: pr: needs review :pray:

#1337 Update Amplify and remove token assertions
  next/frontend/utils/amplifyAssert.ts
  next/frontend/utils/amplifyServer.ts
  next/package-lock.json
  next/package.json
  next/pages/amplify-test.tsx
  next/pages/force-logout.tsx
Labels: pr: fix & ship :ship:

#1401 add application for housing rental for po
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
Labels: pr: fix & ship :ship:

#1403 Change defaults for "Bytová núdza" and "Rizikové faktory"
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#1404 Form playground
  forms-shared/src/form-utils/getObjectFieldInfo.ts
  forms-shared/src/summary-json/SummaryXmlForm.tsx
  next/components/forms/FormPage.tsx
  next/components/forms/FormProviders.tsx
  next/components/forms/FormsPlayground.tsx
  next/components/forms/segments/FormCalculator/FormCalculator.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/steps/Summary/SummaryAdditionalInfo.tsx
  next/components/forms/steps/Summary/SummaryDetails.tsx
  next/components/forms/steps/Summary/useFormSummary.tsx
  next/components/forms/useFormData.tsx
  next/components/forms/useFormFileUpload.tsx
  next/components/forms/useFormRedirects.tsx
  next/components/forms/useFormSend.tsx
  next/components/forms/useFormState.tsx
  next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/package-lock.json
  next/package.json
  next/pages/forms-playground.ts
Labels: pr: needs review :pray:

#1407 Add PR labeler workflow
  .github/workflows/label.yml
Labels: pr: fix & ship :ship:

#1408 Updated forms-shared image naming
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:

#1219 Use xml2js for xml creation #1134
  forms-shared/src/slovensko-sk/containerFiles.ts
  forms-shared/src/slovensko-sk/file-templates/emptyXml.ts
  forms-shared/src/slovensko-sk/file-templates/metaXml.ts
  forms-shared/src/slovensko-sk/generateXml.ts
  forms-shared/src/slovensko-sk/xmlBuilder.ts
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/nases/dtos/xml.dto.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
Labels: pr: fix & ship :ship:

#1452 Render additional info summary PDF
  forms-shared/src/generated-assets/summaryPdfCss.ts
  forms-shared/src/summary-pdf/SummaryPdf.tsx
  forms-shared/src/summary-pdf/renderSummaryPdf.tsx
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-komunitne-zahrady-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-predzahradky-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-1-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-1-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-2-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-2-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-3-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-4-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-4-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-summary-pdf-should-match-snapshot-10-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-summary-pdf-should-match-snapshot-9-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-7-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-8-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-9-snap.png
  forms-shared/tests/summary-pdf/renderSummaryPdf.ts
  nest-forms-backend/src/convert/convert.service.ts
Labels: pr: fix & ship :ship:

#1383 Move cvdmirror
  .github/workflows/cluster-deploy-conditions-konto.yml
  .github/workflows/deploy.yml
  README.md
  cvdmirror/.dockerignore
  cvdmirror/Caddyfile
  cvdmirror/Dockerfile
  cvdmirror/README.md
  cvdmirror/entrypoint.sh
  cvdmirror/health.sh
  cvdmirror/kubernetes/base/.env
  cvdmirror/kubernetes/base/configuration.yml
  cvdmirror/kubernetes/base/kustomization.yml
  cvdmirror/kubernetes/base/service-cvdmirror.yml
  cvdmirror/kubernetes/base/statefulset-cvdmirror.yml
  cvdmirror/kubernetes/envs/Dev/.env
  cvdmirror/kubernetes/envs/Dev/config.json
  cvdmirror/kubernetes/envs/Dev/kustomization.yml
  cvdmirror/kubernetes/envs/Prod/.env
  cvdmirror/kubernetes/envs/Prod/config.json
  cvdmirror/kubernetes/envs/Prod/kustomization.yml
  cvdmirror/kubernetes/envs/Staging/.env
  cvdmirror/kubernetes/envs/Staging/config.json
  cvdmirror/kubernetes/envs/Staging/kustomization.yml
  cvdmirror/package.json
Labels: pr: fix & ship :ship:

#1453 Enable NEXT_PUBLIC_FEATURE_TOGGLE_EID_TAX_WITHOUT_BETA_FLAG in production
  next/.env.bratiska-cli-build.prod
Labels: pr: fix & ship :ship:

#1455 added fetch-depth option
  .github/workflows/deploy.yml
  .github/workflows/validate-and-build.yml
  .github/workflows/validate-forms-shared-konto.yml
Labels: pr: infrastructure, pr: fix & ship :ship:

#1456 Revert "Enable NEXT_PUBLIC_FEATURE_TOGGLE_EID_TAX_WITHOUT_BETA_FLAG in production"
  next/.env.bratiska-cli-build.prod
Labels: pr: fix & ship :ship:

#1459 When sending with eId, let user know immediately in case of NASES error
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1460 Updating forms-shared naming on build and validate pipeline
  .github/workflows/validate-and-build.yml
Labels: pr: fix & ship :ship:
