Repository bratislava/konto.bratislava.sk, pull requests merged in 2024-12, with the labels that each got.

#1920 useIsSSR instead of useIsClient
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/steps/Summary/SummaryDetails.tsx
  next/components/forms/useFormContext.tsx
Labels: pr: fix & ship :ship:

#1665 chore: update tsconfig in tax backend and fix errors
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/admin/utils/tax-detail.helper.ts
  nest-tax-backend/src/app.module.ts
  nest-tax-backend/src/auth/strategies/admin.strategy.ts
  nest-tax-backend/src/noris/noris.service.ts
  nest-tax-backend/src/payment/payment.controller.ts
  nest-tax-backend/src/payment/payment.service.ts
  nest-tax-backend/src/tax/dtos/requests.tax.dto.ts
  nest-tax-backend/src/tax/dtos/response.pdf.dto.ts
  nest-tax-backend/src/tax/tax.controller.ts
  nest-tax-backend/src/tax/tax.service.ts
  nest-tax-backend/src/tax/utils/helpers/pdf.helper.ts
  nest-tax-backend/src/utils/global-dtos/city-account.dto.ts
  nest-tax-backend/src/utils/global-dtos/cognito.dto.ts
  nest-tax-backend/src/utils/guards/dtos/error.dto.ts
  nest-tax-backend/src/utils/guards/errors.guard.ts
  nest-tax-backend/src/utils/subservices/cityaccount.subservice.ts
  nest-tax-backend/src/utils/subservices/cognito.subservice.ts
  nest-tax-backend/src/utils/subservices/dtos/gpwebpay.dto.ts
  nest-tax-backend/src/utils/subservices/gpwebpay.subservice.ts
  nest-tax-backend/src/utils/subservices/qrcode.subservice.ts
  nest-tax-backend/tsconfig.json
Labels: pr: fix & ship :ship:

#1933 Update tax backend openapi and fix errors
  next/clients/openapi-tax/api.ts
  next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
Labels: pr: fix & ship :ship:

#1921 1232: Hide taxes section for legal entities
  next/components/layouts/AccountPageLayout.tsx
  next/pages/dane-a-poplatky/index.tsx
Labels: pr: fix & ship :ship:

#1941 Open only security dependabot PRs in next
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#1957 Deduplicate React
  next/next.config.js
Labels: pr: fix & ship :ship:

#1966 Fix form playground
  next/components/forms/FormsPlayground.tsx
  next/pages/forms-playground.ts
Labels: pr: fix & ship :ship:

#1978 Create technical-issue template
  .github/ISSUE_TEMPLATE/technical-issue
Labels: pr: fix & ship :ship:

#1979 #1833 Tax administrator contact card
  next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
  next/pages/dane-a-poplatky/[year].tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#1980 UI schema in schema
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/src/form-utils/ajvKeywords.ts
  forms-shared/src/form-utils/defaultFormFields.tsx
  forms-shared/src/form-utils/formDefaults.ts
  forms-shared/src/generator/addBaOrderToFields.ts
  forms-shared/src/generator/functions.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/kalkulacky.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step3.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step4.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step5.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step6.ts
  forms-shared/src/summary-json/SummaryXmlForm.tsx
  forms-shared/test-utils/testForm.tsx
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/generator/addBaOrderToFields.ts
  forms-shared/tests/summary-json/getSummaryDisplayValue.tsx
  nest-forms-backend/package-lock.json
  nest-forms-backend/src/forms/forms.service.spec.ts
  nest-forms-backend/src/utils/handlers/text.handler.spec.ts
  nest-forms-backend/src/utils/handlers/text.handler.ts
  next/components/forms/FormPage.tsx
  next/components/forms/FormsPlayground.tsx
  next/components/forms/ThemedForm.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/useFormState.tsx
  next/frontend/utils/formState.ts
  next/package-lock.json
Labels: pr: fix & ship :ship:

#1965 Tax form fix formulas
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step3.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step4.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step5.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step6.ts
  forms-shared/src/tax-form/formulas.ts
  forms-shared/src/tax-form/mapping/shared/oddiel2Shared.ts
  forms-shared/src/tax-form/mapping/shared/oddiel3JedenUcelShared.ts
  forms-shared/src/tax-form/mapping/shared/oddiel3ViacereUcelyShared.ts
  forms-shared/src/tax-form/mapping/shared/oddiel4Shared.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-3-snap.png
  forms-shared/tests/tax-form/__snapshots__/taxForm.ts.snap
Labels: pr: needs review :pray:

#2030 .env.example and docker-compose updates for local nest-forms development
  nest-forms-backend/.env.example
  nest-forms-backend/docker-compose.yml
  nest-forms-backend/package.json
Labels: pr: needs review :pray:

#1977 Add missing information and configuration for initial forms project setup
  forms-shared/README.md
  nest-forms-backend/.env.example
  nest-forms-backend/docker-compose.yml
  nest-forms-backend/package.json
Labels: pr: needs review :pray:

#2031 Delete rfo table from database
  nest-city-account/prisma/migrations/20241218084945_remove_rfo_data/migration.sql
  nest-city-account/prisma/schema.prisma
  nest-city-account/src/magproxy/dtos/uri.ts
  nest-city-account/src/physical-entity/physical-entity.module.ts
  nest-city-account/src/physical-entity/physical-entity.service.spec.ts
  nest-city-account/src/physical-entity/physical-entity.service.ts
  nest-city-account/src/physical-entity/subservices/physical-entity-cron.subservice.ts
  nest-city-account/src/rfo-by-birthnumber/rfo-by-birthnumber.module.ts
  nest-city-account/src/rfo-by-birthnumber/rfo-by-birthnumber.service.spec.ts
  nest-city-account/src/rfo-by-birthnumber/rfo-by-birthnumber.service.ts
  nest-city-account/src/rfo-by-birthnumber/utils/__test__/uri.spec.ts
Labels: pr: fix & ship :ship:

#1994 #1990 Chore: update eslint for tax backend and resolve errors
  nest-tax-backend/.eslintrc.js
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
  nest-tax-backend/src/admin/admin.controller.ts
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/admin/utils/__tests__/tax-detail.helper.spec.ts
  nest-tax-backend/src/admin/utils/tax-detail.helper.ts
  nest-tax-backend/src/auth/guards/tiers.guard.ts
  nest-tax-backend/src/bloomreach/bloomreach.service.ts
  nest-tax-backend/src/noris/noris.dto.ts
  nest-tax-backend/src/noris/noris.service.ts
  nest-tax-backend/src/payment/payment.controller.ts
  nest-tax-backend/src/payment/payment.service.ts
  nest-tax-backend/src/tax/tax.controller.ts
  nest-tax-backend/src/tax/tax.service.ts
  nest-tax-backend/src/utils/guards/errors.guard.ts
  nest-tax-backend/src/utils/middlewares/logger.ts
  nest-tax-backend/src/utils/subservices/__tests__/gpwebpay.subservice.spec.ts
  nest-tax-backend/src/utils/subservices/cityaccount.subservice.ts
  nest-tax-backend/src/utils/subservices/gpwebpay.subservice.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2021 1864: Add taxes banner to announcements
  next/assets/images/banner-dane-new.png
  next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
  next/public/locales/sk/account.json
Labels: pr: needs review :pray:
