Repository bratislava/konto.bratislava.sk, pull requests merged in 2024-01, with the labels that each got.

#715 Dane improvements v22
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/segments/PropertyTaxCalculator/PropertyTaxCalculator.tsx
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
  next/components/forms/simple-components/Waves/Waves.tsx
  next/components/forms/steps/Summary/SummaryArrayTemplateRJSF.tsx
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/components/forms/useFormModals.tsx
  next/components/forms/useFormState.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/frontend/types/initialFormData.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti-dev.ts
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
  next/public/locales/sk/forms.json
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
Labels: pr: fix & ship :ship:

#716 Dane improvements v23
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
Labels: pr: needs review :pray:

#718 Dane improvements v24
  next/schema-generator/generator/functions.ts
Labels: pr: needs review :pray:

#721 Dane improvements v25
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/FormMarkdown.tsx
  next/components/forms/simple-components/ButtonNew.tsx
  next/components/forms/useFormModals.tsx
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/osoby.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step1.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: needs review :pray:

#727 Dane improvements v26
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
  next/components/forms/simple-components/ModalV2.tsx
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
  next/pages/typography.css
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#719 Add dots in the end of sentence for snackbars and errors
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#720 Remove select-none on upload component
  next/components/forms/widget-components/Upload/Upload.tsx
Labels: pr: fix & ship :ship:

#713 Change spacing for profile icons
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
Labels: pr: fix & ship :ship:

#729 Dane improvements v27
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
  next/public/locales/sk/forms.json
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
Labels: pr: fix & ship :ship:

#731 Dane improvements v28
  next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
  next/components/forms/segments/PropertyTaxCalculator/PropertyTaxCalculator.tsx
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-wrappers/BAArrayFieldItemTemplate.tsx
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
Labels: pr: needs review :pray:

#733 Dane improvements v29
  next/components/forms/widget-wrappers/BAArrayFieldTemplate.tsx
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/step6.ts
  next/schema-generator/generator/uiOptionsTypes.ts
Labels: pr: needs review :pray:

#734 Dane improvements v30
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/info-components/TaxFormLandingPageCard.tsx
  next/components/forms/simple-components/ButtonNew.tsx
  next/public/locales/sk/forms.json
Labels: pr: needs review :pray:

#736 Dane improvemnents v31
  next/components/forms/TaxFormLandingPage.tsx
  next/public/locales/sk/forms.json
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti/osoby.ts
Labels: pr: fix & ship :ship:

#714 Move non verified alert outside of user profile header
  next/components/forms/segments/UserProfile/UserProfileDetail.tsx
  next/components/forms/segments/UserProfile/UserProfileSectionHeader.tsx
Labels: pr: fix & ship :ship:

#738 Allow searchengines on production
  next/pages/api/robots.ts
Labels: pr: fix & ship :ship:

#743 Dane improvements v33
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModalState.tsx
  next/components/forms/useFormModals.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/public/locales/sk/forms.json
Labels: pr: needs review :pray:

#740 Add custom errors for uploaded files in forms
  next/components/forms/useFormFileUpload.tsx
  next/components/forms/widget-components/Upload/UploadFileCard.tsx
  next/frontend/types/formFileUploadTypes.ts
  next/frontend/utils/formFileUpload.ts
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#732 Remove PageWrapper and all references due to not being used
  next/components/forms/FormPageWrapper.tsx
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/segments/LoginRegisterNavBar/LoginRegisterNavBar.tsx
  next/components/forms/simple-components/PrettyBytes.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/components/layouts/FormPageLayout.tsx
  next/components/layouts/LoginRegisterLayout.tsx
  next/components/layouts/PageWrapper.tsx
  next/components/layouts/TestUserProfileLayout.tsx
  next/pages/aktivacia-konta.tsx
  next/pages/dane-a-poplatky/2023.tsx
  next/pages/dane-a-poplatky/index.tsx
  next/pages/get-jwt.tsx
  next/pages/index.tsx
  next/pages/logout.tsx
  next/pages/mestske-sluzby.tsx
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti-dev.ts
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
  next/pages/moj-profil.tsx
  next/pages/moje-ziadosti/[ziadost].tsx
  next/pages/moje-ziadosti/index.tsx
  next/pages/overenie-identity.tsx
  next/pages/platba/stav.tsx
  next/pages/pomoc.tsx
  next/pages/prihlasenie.tsx
  next/pages/registracia.tsx
  next/pages/styleguide.tsx
  next/pages/zabudnute-heslo.tsx
  next/pages/zmena-emailu.tsx
  next/pages/zmena-hesla.tsx
Labels: pr: fix & ship :ship:

#728 Fix accessibility issues, Add nav controls via keyboard arrows
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSectionHeader/AccountSectionHeader.tsx
  next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
  next/components/forms/segments/AccountSections/HelpSection/HelpSection.tsx
  next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
  next/components/forms/segments/UserProfile/UserConsent.tsx
  next/components/forms/segments/UserProfile/UserProfileDetailsButtons.tsx
  next/components/forms/segments/UserProfile/UserProfileSectionHeader.tsx
  next/components/forms/simple-components/Accordion.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/forms/simple-components/Brand.tsx
  next/components/forms/simple-components/Button.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/pages/_app.tsx
  next/public/locales/sk/account.json
Labels: pr: needs review :pray:

#735 Generate and update form schemas cli tool
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti-dev.ts
  next/schema-generator/.env.example
  next/schema-generator/.gitignore
  next/schema-generator/README.md
  next/schema-generator/cli.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/kalkulacky.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/osoby.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/pravnyVztahSpoluvlastnictvo.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/statCiselnik.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/stavbyBase.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step1.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step2.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step3.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step4.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step5.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step6.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step7.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/step8.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/stepEnum.ts
  next/schema-generator/definitions/priznanie-k-dani-z-nehnutelnosti/vyplnitKrokRadio.ts
  next/schema-generator/definitions/priznanieKDaniZNehnutelnosti.ts
  next/schema-generator/definitions/stanovisko-k-investicnemu-zameru.ts
  next/schema-generator/definitions/zavazne-stanovisko-k-investicnej-cinnosti.ts
  next/schema-generator/package.json
  next/schema-generator/update.ts
  next/schema-generator/yarn.lock
Labels: pr: fix & ship :ship:

#748 Add missing provider
  next/pages/_app.tsx
Labels: pr: needs review :pray:

#661 #28 show pages for unauthenticated user
  next/components/forms/FormPageWrapper.tsx
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/HambergerMenu/HamburgerMenu.tsx
  next/components/forms/segments/NavBar/NavBar.tsx
  next/components/forms/segments/NavBar/NavBarLink.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/components/layouts/FormPageLayout.tsx
  next/components/layouts/TestUserProfileLayout.tsx
  next/pages/dane-a-poplatky/2023.tsx
  next/pages/dane-a-poplatky/index.tsx
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/[slug]/index.tsx
  next/pages/moj-profil.tsx
  next/pages/moje-ziadosti/index.tsx
  next/pages/overenie-identity.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#749 Dane improvements v35
  next/assets/ui-icons/dane_48px.svg
  next/assets/ui-icons/hrad_48px.svg
  next/assets/ui-icons/index.ts
  next/assets/ui-icons/pdf_48px.svg
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/info-components/TaxFormLandingPageCard.tsx
Labels: pr: needs review :pray:

#752 Disable PDF download for tax form from three dots / menu list
  next/components/forms/simple-components/FormHeader.tsx
  next/components/forms/steps/MenuList.tsx
Labels: pr: needs review :pray:

#751 vop_agreement_content update
  next/public/locales/sk/forms.json
Labels: pr: needs review :pray:

#753 Better tracking of form instances in plausible
  next/components/forms/FormPageWrapper.tsx
  next/pages/_app.tsx
Labels: pr: fix & ship :ship:

#754 Disable status bar about PO registrations
  next/public/locales/sk/common.json
Labels: pr: fix & ship :ship:

#756 Fix plausible views on form pages
  next/components/forms/FormPageWrapper.tsx
Labels: pr: fix & ship :ship:

#757 Dane improvements v37
  next/components/forms/steps/Summary/SummaryFormLegalText.tsx
  next/public/locales/sk/forms.json
Labels: pr: needs review :pray:

#759 [#758] add useEffect that sets redirect target every time it changes
  next/frontend/hooks/useLoginRegisterRedirect.tsx
Labels: pr: fix & ship :ship:

#766 Custom cognito tax form beta attribute
  next/frontend/dtos/accountDto.ts
Labels: pr: fix & ship :ship:

#767 JSON export/import in forms
  next/components/forms/FormPage.tsx
  next/components/forms/FormUploadXmlJson.tsx
  next/components/forms/simple-components/FormHeader.tsx
  next/components/forms/steps/MenuList.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/public/locales/sk/forms.json
Labels: pr: needs review :pray:

#768 Dane improvements v40
  next/components/forms/TaxFormLandingPage.tsx
  next/components/forms/info-components/TaxFormLandingPageCard.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/signer/mapDitecError.ts
  next/components/forms/signer/signerTypes.ts
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/signer/useFormSigner.ts
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/components/forms/steps/Summary/SummaryFormLegalText.tsx
  next/components/forms/steps/Summary/SummaryFormSignature.tsx
  next/components/forms/steps/SummaryHeader.tsx
  next/components/forms/useFormModals.tsx
  next/frontend/utils/formSummary.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti.ts
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#769 Form data base64
  next/components/forms/useFormSend.tsx
  next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
Labels: pr: fix & ship :ship:

#770 Debug log signature
  next/components/forms/signer/useFormSignature.tsx
Labels: pr: fix & ship :ship:

#761 [#677] fix link address
  next/frontend/constants/constants.tsx
Labels: pr: fix & ship :ship:

#774 Amplify lax cookie
  next/frontend/utils/amplify.ts
Labels: pr: needs review :pray:

#775 Revert "Amplify lax cookie"
  next/frontend/utils/amplify.ts
Labels: pr: needs review :pray:

#776 Add path in login link in NavBar
  next/components/forms/segments/NavBar/NavBar.tsx
Labels: pr: needs review :pray:

#777 Revert "Add path in login link in NavBar"
  next/components/forms/segments/NavBar/NavBar.tsx
Labels: pr: needs review :pray:

#781 No menu download pdf for tax form
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
Labels: pr: needs review :pray:

#782 Add tax link to services
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/frontend/api/constants.tsx
  next/frontend/constants/constants.tsx
  next/public/locales/sk/account.json
Labels: pr: needs review :pray:

#783 Fix button
  next/components/forms/steps/Summary/SummaryFormControls.tsx
Labels: pr: needs review :pray:

#784 Change intro section
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
Labels: pr: needs review :pray:

#785 Dane improvements v48
  next/components/forms/TaxFormLandingPage.tsx
Labels: pr: needs review :pray:

#789 Dane improvements v49
  next/__tests__/form-file-upload.test.tsx
  next/components/forms/FormPage.tsx
  next/components/forms/FormPageWrapper.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/signer/useFormSignerLoader.tsx
  next/components/forms/simple-components/FormHeader.tsx
  next/components/forms/steps/MenuList.tsx
  next/components/forms/steps/Summary/FormSummary.tsx
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/components/forms/steps/Summary/SummaryFormLegalText.tsx
  next/components/forms/steps/Summary/SummaryFormSignature.tsx
  next/components/forms/steps/Summary/SummaryWidgetRJSF.tsx
  next/components/forms/steps/Summary/useFormSummary.tsx
  next/components/forms/steps/SummaryHeader.tsx
  next/components/forms/useFormComponent.tsx
  next/components/forms/useFormContext.tsx
  next/components/forms/useFormFileUpload.tsx
  next/components/forms/useFormModals.tsx
  next/components/forms/useFormRedirects.tsx
  next/components/forms/useFormSend.tsx
  next/components/forms/useFormState.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-components/Upload/UploadFileCard.tsx
  next/components/forms/widget-components/Upload/UploadFilesList.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/frontend/types/initialFormData.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti-dev.ts
Labels: pr: needs review :pray:

#793 fix: KEDA scaller when metric is fluctuating
  next/kubernetes/envs/Prod/scaler.yml
Labels: pr: infrastructure
