Repository bratislava/konto.bratislava.sk, pull requests merged in 2025-07, with the labels that each got.

#3006 Setup S3 bucket
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/next.config.ts
  strapi/config/env/production/plugins.ts
  strapi/config/middlewares.ts
  strapi/kubernetes/base/.env
  strapi/package-lock.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#2992 #83 Municipal services from strapi
  next/clients/graphql-strapi/api.ts
  next/clients/graphql-strapi/queries/Homepage.graphql
  next/clients/graphql-strapi/queries/MunicipalService.graphql
  next/clients/graphql-strapi/queries/MunicipalServicesPage.graphql
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/components/forms/segments/MunicipalServiceCard/MunicipalServiceCard.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/frontend/constants/constants.tsx
  next/pages/index.css
  next/pages/index.tsx
  next/pages/mestske-sluzby.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#3010 Add missing region
  strapi/config/env/production/plugins.ts
  strapi/kubernetes/base/.env
Labels: pr: fix & ship :ship:

#3011 Fix double MinIO credentials in Strapi deployment
  strapi/kubernetes/base/deployment.yml
Labels: pr: needs review :pray:

#3013 #896 Homepage announcements from strapi
  next/clients/graphql-strapi/api.ts
  next/clients/graphql-strapi/queries/Homepage.graphql
  next/clients/graphql-strapi/queries/HomepageAnnouncement.graphql
  next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/Announcements/AnnouncementBlockStrapi.tsx
  next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodBanner.tsx
  next/pages/index.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#3012 885 - Save tax employee info for each tax payer from Noris
  nest-tax-backend/prisma/migrations/20250702110129_move_tax_employee_to_tax_payer/migration.sql
  nest-tax-backend/prisma/migrations/20250702141655_rename_tax_employee_to_tax_administrator/migration.sql
  nest-tax-backend/prisma/schema.prisma
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/admin/utils/__tests__/admin.helper.spec.ts
  nest-tax-backend/src/admin/utils/admin.helper.ts
  nest-tax-backend/src/admin/utils/testing-tax-mock.ts
  nest-tax-backend/src/tax/dtos/response.tax.dto.ts
  nest-tax-backend/src/tax/tax.service.ts
  next/pages/dane-a-poplatky/index.tsx
  openapi-clients/tax/api.ts
Labels: pr: fix & ship :ship:

#3016 Update Tax administrator info on import of taxes
  nest-tax-backend/src/admin/admin.service.ts
Labels: pr: fix & ship :ship:

#3017 Create new "Žiadosť o územnoplánovaciu informáciu" dev form
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/schemas/ziadostOUzemnoplanovaciuInformaciu.ts
Labels: pr: fix & ship :ship:

#3054 fix id used when requesting user from database
  nest-city-account/src/user/user.service.ts
Labels: pr: fix & ship :ship:

#3015 Wait for connection on noris tax update
  nest-tax-backend/src/noris/__tests__/noris.service.spec.ts
  nest-tax-backend/src/noris/noris.service.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2994 Adjust ginis service processing
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
Labels: pr: fix & ship :ship:

#3058 #434 Žiadosť o územnoplánovaciu informáciu final changes
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/example-forms/exampleForms.ts
  forms-shared/src/example-forms/examples/ziadostOUzemnoplanovaciuInformaciuExample.ts
  forms-shared/src/schemas/tsb/objednavkaInformativnehoZakresuSieti.ts
  forms-shared/src/schemas/tsb/ziadostOStanoviskoKProjektovejDokumentacii.ts
  forms-shared/src/schemas/ziadostOUzemnoplanovaciuInformaciu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/form-utils/__snapshots__/formDataExtractors.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-uzemnoplanovaciu-informaciu-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-uzemnoplanovaciu-informaciu-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-uzemnoplanovaciu-informaciu-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-uzemnoplanovaciu-informaciu-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-uzemnoplanovaciu-informaciu-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-uzemnoplanovaciu-informaciu-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-uzemnoplanovaciu-informaciu-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-uzemnoplanovaciu-informaciu-example-summary-pdf-should-match-snapshot-2-snap.png
Labels: pr: fix & ship :ship:

#3061 #434 UPI Add missing dot
  forms-shared/src/schemas/ziadostOUzemnoplanovaciuInformaciu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#3080 Payment reporting multiple recipients and better logging
  nest-tax-backend/src/admin/dtos/requests.dto.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.controller.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.service.ts
  nest-tax-backend/src/tasks/tasks.service.ts
  nest-tax-backend/src/utils/subservices/email.subservice.ts
  openapi-clients/tax/api.ts
Labels: pr: fix & ship :ship:

#3060 Remove form state SENDING_TO_NASES
  docs/runbook/formulare-support.md
  nest-forms-backend/prisma/migrations/20250718100858_remove_sending_to_nases_form_state/migration.sql
  nest-forms-backend/prisma/schema.prisma
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
  next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
  next/frontend/hooks/useFormStateComponents.tsx
  next/public/locales/sk/account.json
  openapi-clients/forms/api.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#3086 #104 Use new auth old endpoints V3
  nest-forms-backend/src/files/__tests__/files.controller.spec.ts
  nest-forms-backend/src/files/files.controller.ts
  nest-forms-backend/src/files/files.service.ts
Labels: pr: fix & ship :ship:

#3087 Add UPI feedback link
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#3090 [bratislava/private-konto.bratislava.sk#869] await trackEventConsents
  nest-city-account/src/bloomreach/bloomreach.service.ts
  nest-city-account/src/user/dtos/gdpr.user.dto.ts
  nest-city-account/src/user/user.service.ts
  nest-city-account/src/user/utils/subservice/database.subservice.ts
  next/package-lock.json
Labels: pr: fix & ship :ship:

#3120 fix: Add ParseIntPipe to 'year' query
  nest-tax-backend/src/tax/tax.controller.ts
Labels: pr: fix & ship :ship:

#3062 885 Tax administrator from Tax BE
  next/backend/utils/strapi-tax-administrator.ts
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCards.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesTaxAdministratorCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeesSection.tsx
  next/pages/dane-a-poplatky/[year].tsx
  next/pages/dane-a-poplatky/index.tsx
Labels: pr: fix & ship :ship:

#3124 Change ginis endpoints after ginis server migration
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
Labels: pr: fix & ship :ship:
