Repository bratislava/konto.bratislava.sk, pull requests merged in 2025-04, with the labels that each got.

#2580 #80 Komunitné záhrady a predzáhradky - change send policy
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#2581 803 Add Žiadosť o sprístupnenie informácií podľa zákona č. 211/2000 Z.z. card
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/frontend/constants/constants.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#2582 Implement skipGinisStateUpdate flag
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/ginis/subservices/ginis-tasks.subservice.ts
Labels: pr: fix & ship :ship:

#2583 Update packages 2025 04 02 + regenerate clients
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/src/generated-assets/summaryPdfCss.ts
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  next/package-lock.json
  next/package.json
  openapi-clients/tax/api.ts
Labels: pr: fix & ship :ship:

#2585 Very temporary fix for SUR forms subject
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/utils/handlers/text.handler.spec.ts
  nest-forms-backend/src/utils/handlers/text.handler.ts
Labels: pr: fix & ship :ship:

#2586 Conditional message in thank you form section
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#2610 Upload taxes each 10 minutes instead of 30
  nest-city-account/src/utils/subservices/tasks.subservice.ts
Labels: pr: fix & ship :ship:

#2485 #842 propagate changes in cognito user attributes to Bloomreach
  nest-city-account/.env.example
  nest-city-account/README.md
  nest-city-account/src/admin/admin.service.ts
  nest-city-account/src/bloomreach/bloomreach.module.ts
  nest-city-account/src/bloomreach/bloomreach.service.ts
  nest-city-account/src/main.ts
  nest-city-account/src/user-verification/verification.module.ts
  nest-city-account/src/user-verification/verification.service.ts
  nest-city-account/src/user/user.controller.ts
  nest-city-account/src/utils/subservices/cognito.subservice.ts
  next/components/forms/segments/UserProfile/UserProfileView.tsx
  next/frontend/hooks/useUser.ts
  next/pages/zmena-emailu.tsx
  openapi-clients/city-account/api.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2309 Feat: import tax ruling date from noris
  nest-tax-backend/prisma/migrations/20250217134248_add_fields_for_tax_ruling_date/migration.sql
  nest-tax-backend/prisma/schema.prisma
  nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/noris/__tests__/noris.service.spec.ts
  nest-tax-backend/src/noris/noris.dto.ts
  nest-tax-backend/src/noris/noris.queries.ts
  nest-tax-backend/src/noris/noris.service.ts
  nest-tax-backend/src/tasks/tasks.service.ts
  nest-tax-backend/src/tax/dtos/requests.tax.dto.ts
  nest-tax-backend/src/utils/constants.ts
  nest-tax-backend/src/utils/types/types.prisma.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2612 Create release.yml file to format releases
  .github/release.yml
Labels: pr: fix & ship :ship:

#2613 859 Form data extractors
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/form-utils/evaluateFormDataExtractor.ts
  forms-shared/src/form-utils/formDataExtractors.ts
  forms-shared/src/generator/functions/schema.ts
  forms-shared/src/generator/uiOptionsTypes.ts
  forms-shared/src/schemas/komunitneZahrady.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/energetickeZhodnotenieOdpaduVZevo.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/src/schemas/olo/uzatvorenieZmluvyONakladaniSOdpadom.ts
  forms-shared/src/schemas/oznamenieOPoplatkovejPovinnostiZaKomunalneOdpady.ts
  forms-shared/src/schemas/predzahradky.ts
  forms-shared/src/schemas/priznanieKDaniZNehnutelnosti.ts
  forms-shared/src/schemas/showcase.ts
  forms-shared/src/schemas/stanoviskoKInvesticnemuZameru.ts
  forms-shared/src/schemas/tsb/objednavkaInformativnehoZakresuSieti.ts
  forms-shared/src/schemas/tsb/objednavkaVytyceniaPodzemnychVedeniVerejnehoOsvetlenia.ts
  forms-shared/src/schemas/tsb/ziadostOStanoviskoKProjektovejDokumentacii.ts
  forms-shared/src/schemas/tsb/ziadostOUmiestnenieInehoZariadeniaNaStoziarVerejnehoOsvetlenia.ts
  forms-shared/src/schemas/zavazneStanoviskoKInvesticnejCinnosti.ts
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/src/schemas/ziadostOSlobodnyPristupKInformaciam.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/form-utils/__snapshots__/formDataExtractors.ts.snap
  forms-shared/tests/form-utils/formDataExtractors.ts
  nest-forms-backend/src/forms/forms.service.ts
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/nases/dtos/requests.dto.ts
  nest-forms-backend/src/nases/dtos/responses.dto.ts
  nest-forms-backend/src/nases/nases.controller.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
  nest-forms-backend/src/utils/handlers/text.handler.spec.ts
  nest-forms-backend/src/utils/handlers/text.handler.ts
  nest-forms-backend/src/utils/subservices/__test__/sharepoint.subservice.spec.ts
  nest-forms-backend/src/utils/subservices/sharepoint.subservice.ts
  next/components/forms/FormLandingPage.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/components/forms/segments/FormModals/FormModals.tsx
  next/components/styleguide/showcases/MyApplicationsCardShowCase.tsx
  next/frontend/utils/general.ts
  next/pages/mestske-sluzby/[slug]/index.tsx
  next/public/locales/sk/forms.json
  openapi-clients/forms/api.ts
Labels: pr: fix & ship :ship:

#2459 Card Payment Reporting
  nest-tax-backend/README.md
  nest-tax-backend/kubernetes/base/deployment.yml
  nest-tax-backend/kubernetes/envs/Prod/.env
  nest-tax-backend/kubernetes/envs/Prod/secrets/reporting.secret.yml
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  nest-tax-backend/prisma/migrations/20250408175517_add_csv_files_and_config/migration.sql
  nest-tax-backend/prisma/schema.prisma
  nest-tax-backend/src/app.module.ts
  nest-tax-backend/src/card-payment-reporting/__tests__/card-payment-reporting.service.spec.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.module.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.service.ts
  nest-tax-backend/src/tasks/__tests__/tasks.service.spec.ts
  nest-tax-backend/src/tasks/tasks.module.ts
  nest-tax-backend/src/tasks/tasks.service.ts
  nest-tax-backend/src/utils/subservices/__tests__/sftp-file.subservice.spec.ts
  nest-tax-backend/src/utils/subservices/email.subservice.ts
  nest-tax-backend/src/utils/subservices/sftp-file.subservice.ts
Labels: pr: fix & ship :ship:

#2578 Endpoint for creating and deleting testing taxes
  nest-tax-backend/src/admin/admin.controller.ts
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/admin/dtos/requests.dto.ts
  nest-tax-backend/src/admin/utils/testing-tax-mock.ts
  nest-tax-backend/src/auth/guards/not-production.guard.ts
Labels: pr: fix & ship :ship:

#2616 Fix TSB email
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#2617 Remove verifyUserByEidToken
  nest-forms-backend/src/common/utils/city-account.ts
  nest-forms-backend/src/nases/nases.controller.ts
  nest-forms-backend/src/nases/nases.service.ts
  nest-forms-backend/src/utils/decorators/request.decorator.ts
Labels: pr: fix & ship :ship:

#2619 Fix: env vars in payment reporting
  nest-tax-backend/README.md
  nest-tax-backend/kubernetes/envs/Dev/.env
  nest-tax-backend/kubernetes/envs/Staging/.env
  nest-tax-backend/prisma/migrations/20250411124652_add_dummy_variable_to_config/migration.sql
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.service.ts
Labels: pr: fix & ship :ship:

#2620 Fix secrets for card payment reporting
  nest-tax-backend/kubernetes/envs/Dev/kustomization.yml
  nest-tax-backend/kubernetes/envs/Dev/secrets/reporting.secret.yml
  nest-tax-backend/kubernetes/envs/Prod/kustomization.yml
  nest-tax-backend/kubernetes/envs/Prod/secrets/reporting.secret.yml
  nest-tax-backend/kubernetes/envs/Staging/kustomization.yml
  nest-tax-backend/kubernetes/envs/Staging/secrets/reporting.secret.yml
Labels: pr: fix & ship :ship:

#2615 Update packages 2025 04 10 + replace libxmljs/xsd-validator with libxml2-wasm
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/src/generated-assets/summaryPdfCss.ts
  forms-shared/src/slovensko-sk/validateXml.ts
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/signer/signer.service.ts
  nest-forms-backend/src/utils/constants/error.alerts.ts
  next/package-lock.json
  next/package.json
Labels: pr: fix & ship :ship:

#2641 Add email secrets and documentation
  nest-tax-backend/kubernetes/base/deployment.yml
  nest-tax-backend/kubernetes/envs/Dev/kustomization.yml
  nest-tax-backend/kubernetes/envs/Dev/secrets/email.secret.yml
  nest-tax-backend/kubernetes/envs/Prod/kustomization.yml
  nest-tax-backend/kubernetes/envs/Prod/secrets/email.secret.yml
  nest-tax-backend/kubernetes/envs/Staging/kustomization.yml
  nest-tax-backend/kubernetes/envs/Staging/secrets/email.secret.yml
  nest-tax-backend/src/utils/subservices/email.subservice.ts
Labels: pr: fix & ship :ship:

#2644 Skip nases outbox if we are sending the message to ourselves
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2647 Remove tax card for PO
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
Labels: pr: fix & ship :ship:

#2643 793 Forms BE OpenAPI clients
  .github/workflows/validate-nest-prisma-konto.yml
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/scripts/generateOpenApiClient.ts
  nest-forms-backend/src/admin/admin.module.ts
  nest-forms-backend/src/auth/auth.module.ts
  nest-forms-backend/src/auth/decorators/user-info-pipe.module.ts
  nest-forms-backend/src/auth/decorators/user-info.decorator.ts
  nest-forms-backend/src/clients/clients.module.ts
  nest-forms-backend/src/clients/clients.service.ts
  nest-forms-backend/src/convert/convert.controller.ts
  nest-forms-backend/src/convert/convert.module.ts
  nest-forms-backend/src/files/__tests__/files.controller.spec.ts
  nest-forms-backend/src/files/files.controller.ts
  nest-forms-backend/src/files/files.module.ts
  nest-forms-backend/src/forms/forms.controller.ts
  nest-forms-backend/src/forms/forms.helper.spec.ts
  nest-forms-backend/src/forms/forms.helper.ts
  nest-forms-backend/src/forms/forms.module.ts
  nest-forms-backend/src/ginis/ginis.controller.spec.ts
  nest-forms-backend/src/ginis/ginis.controller.ts
  nest-forms-backend/src/ginis/ginis.module.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.module.ts
  nest-forms-backend/src/nases/nases.controller.ts
  nest-forms-backend/src/nases/nases.module.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
  nest-forms-backend/src/signer/signer.controller.ts
  nest-forms-backend/src/signer/signer.module.ts
  nest-forms-backend/src/utils/clients/cityAccountApi.ts
  nest-forms-backend/src/utils/clients/openapi-city-account/.gitignore
  nest-forms-backend/src/utils/clients/openapi-city-account/.npmignore
  nest-forms-backend/src/utils/clients/openapi-city-account/.openapi-generator-ignore
  nest-forms-backend/src/utils/clients/openapi-city-account/.openapi-generator/FILES
  nest-forms-backend/src/utils/clients/openapi-city-account/.openapi-generator/VERSION
  nest-forms-backend/src/utils/clients/openapi-city-account/api.ts
  nest-forms-backend/src/utils/clients/openapi-city-account/base.ts
  nest-forms-backend/src/utils/clients/openapi-city-account/common.ts
  nest-forms-backend/src/utils/clients/openapi-city-account/configuration.ts
  nest-forms-backend/src/utils/clients/openapi-city-account/git_push.sh
  nest-forms-backend/src/utils/clients/openapi-city-account/index.ts
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/.gitignore
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/.npmignore
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/.openapi-generator-ignore
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/.openapi-generator/FILES
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/.openapi-generator/VERSION
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/api.ts
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/base.ts
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/common.ts
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/configuration.ts
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/git_push.sh
  nest-forms-backend/src/utils/clients/openapi-slovensko-sk/index.ts
  nest-forms-backend/src/utils/clients/slovenskoSkApi.ts
  nest-forms-backend/src/utils/decorators/request.decorator.ts
Labels: pr: fix & ship :ship:

#2648 Fix Next form definition
  forms-shared/src/signer/signature.ts
  forms-shared/src/string-templates/renderTemplate.ts
  next/components/forms/FormLandingPage.tsx
  next/components/forms/FormsPlayground.tsx
  next/components/forms/clientFormDefinitions.ts
  next/components/forms/serializableFormDefinition.ts
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/useFormContext.tsx
  next/pages/forms-playground.ts
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/[slug]/index.tsx
  next/pages/mestske-sluzby/dev/[slug].ts
Labels: pr: fix & ship :ship:

#2614 835 ginis attachment upload replacement
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/config/ba-config.ts
  nest-forms-backend/src/config/environment-variables.ts
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.spec.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.ts
  nest-forms-backend/src/ginis/subservices/ginis-tasks.subservice.ts
  nest-forms-backend/src/ginis/subservices/ginis.helper.spec.ts
  nest-forms-backend/src/ginis/subservices/ginis.helper.ts
Labels: pr: fix & ship :ship:

#2673 860 ko ginis owner
  nest-forms-backend/src/ginis/ginis.controller.spec.ts
  nest-forms-backend/src/ginis/ginis.controller.ts
  nest-forms-backend/src/ginis/subservices/ginis.helper.ts
  next/frontend/utils/ginis.ts
Labels: pr: fix & ship :ship:

#2674 Remove newline from reporting secrets
  nest-tax-backend/kubernetes/envs/Dev/secrets/reporting.secret.yml
Labels: pr: fix & ship :ship:

#2677 Derive object required automatically in schema generator
  forms-shared/src/generator/functions/step.ts
  forms-shared/src/generator/object.ts
  forms-shared/src/schemas/komunitneZahrady.ts
  forms-shared/src/schemas/olo/docisteniStanovistaZbernychNadob.ts
  forms-shared/src/schemas/olo/koloTaxi.ts
  forms-shared/src/schemas/olo/mimoriadnyOdvozAZhodnotenieOdpadu.ts
  forms-shared/src/schemas/olo/odvozObjemnehoOdpaduValnikom.ts
  forms-shared/src/schemas/olo/odvozOdpaduVelkokapacitnymAleboLisovacimKontajnerom.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/shared/zevoShared.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/src/schemas/oznamenieOPoplatkovejPovinnostiZaKomunalneOdpady.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/kalkulacky.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/osoby.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/stavbyBase.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step2.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step3.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step4.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step5.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step6.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/vyplnitKrokRadio.ts
  forms-shared/src/schemas/shared/fields.ts
  forms-shared/src/schemas/showcase.ts
  forms-shared/src/schemas/stanoviskoKInvesticnemuZameru.ts
  forms-shared/src/schemas/tsb/objednavkaInformativnehoZakresuSieti.ts
  forms-shared/src/schemas/tsb/objednavkaVytyceniaPodzemnychVedeniVerejnehoOsvetlenia.ts
  forms-shared/src/schemas/tsb/shared/getObjednavatelZiadatelStep.ts
  forms-shared/src/schemas/tsb/ziadostOUmiestnenieInehoZariadeniaNaStoziarVerejnehoOsvetlenia.ts
  forms-shared/src/schemas/zavazneStanoviskoKInvesticnejCinnosti.ts
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/src/schemas/ziadostOSlobodnyPristupKInformaciam.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/form-utils/defaultFormState.ts
  forms-shared/tests/form-utils/fileUtils.ts
  forms-shared/tests/form-utils/omitExtraData.ts
  forms-shared/tests/summary-json/getSummaryDisplayValue.tsx
  forms-shared/tests/summary-renderer/validateSummary.ts
  tests/cypress/e2e/form/formRealEstateTaxReturn.cy.ts
  tests/cypress/support/commands/form.ts
Labels: pr: fix & ship :ship:

#2683 Remove legacy Amplify assertion
  next/pages/dane-a-poplatky/[year].tsx
Labels: pr: fix & ship :ship:

#2684 Recreate file stream for each ginis upload file retry
  nest-forms-backend/src/ginis/ginis.service.ts
Labels: pr: fix & ship :ship:

#2686 Create useStrapiTax
  next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCards.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesInPreparationCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useStrapiTax.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeesSection.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouSection.tsx
  next/pages/dane-a-poplatky/[year].tsx
  next/pages/dane-a-poplatky/index.tsx
  next/pages/platba/stav.tsx
Labels: pr: fix & ship :ship:

#2682 add year to successful page after payment
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouSection.tsx
Labels: pr: fix & ship :ship:

#2681 Implement ginis file upload string length restrictions
  nest-forms-backend/src/ginis/subservices/ginis-api.service.ts
Labels: pr: fix & ship :ship:

#2687 Make update query more effective
  nest-tax-backend/src/admin/__tests__/admin.service.spec.ts
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/noris/__tests__/noris.service.spec.ts
  nest-tax-backend/src/noris/noris.queries.ts
  nest-tax-backend/src/noris/noris.service.ts
  nest-tax-backend/src/tasks/tasks.service.ts
  nest-tax-backend/src/utils/constants.ts
  nest-tax-backend/src/utils/types/types.prisma.ts
Labels: pr: fix & ship :ship:

#2679 [#870] fix consent type in userProfileConsents
  next/components/forms/segments/UserProfile/UserProfileConsents.tsx
Labels: pr: fix & ship :ship:

#2712 Fix passing year to tax installments
  next/components/forms/simple-components/AccordionPaymentSchedule.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#2711 Fix reporting files with returned fee
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.service.ts
Labels: pr: fix & ship :ship:

#2688 Remove tax PDF queue usage
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/config/ba-config.ts
  nest-forms-backend/src/config/environment-variables.ts
  nest-forms-backend/src/convert/convert.service.spec.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/tax/processor.ts
  nest-forms-backend/src/tax/tax.module.ts
  nest-forms-backend/src/tax/tax.service.ts
  nest-forms-backend/src/tax/worker.ts
Labels: pr: fix & ship :ship:

#2713 TSB pravnicka osoba fix + email forms status in my applications
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/tsb/shared/getObjednavatelZiadatelStep.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/patchApplicationFormIfNeededClient.ts
  next/components/forms/segments/AccountSections/MyApplicationsSection/patchApplicationFormIfNeededServer.ts
  next/pages/moje-ziadosti/[ziadost].tsx
  next/pages/moje-ziadosti/index.tsx
Labels: pr: fix & ship :ship:

#2716 Put SharepointSubservice into correct module
  nest-forms-backend/src/app.module.ts
  nest-forms-backend/src/ginis/ginis.module.ts
Labels: pr: fix & ship :ship:

#2718 FIX: Do not import taxes without "pohladavka"
  nest-tax-backend/src/noris/noris.queries.ts
Labels: pr: fix & ship :ship:

#2680 Fix tax form viacere ucely without calculator
  forms-shared/src/example-forms/exampleForms.ts
  forms-shared/src/example-forms/examples/priznanieKDaniZNehnutelnostiExample5NoCalculators.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/step5.ts
  forms-shared/src/tax-form/mapping/shared/oddiel3ViacereUcelyShared.ts
  forms-shared/src/tax-form/types.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/form-utils/__snapshots__/formDataExtractors.ts.snap
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-7-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-pdf-should-match-snapshot-8-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-7-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-8-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-pdf-should-match-snapshot-9-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-1-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-2-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-3-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-4-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-5-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-6-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-7-snap.png
  forms-shared/tests/tax-form/__image_snapshots__/tax-form-ts-tax-form-pdf-should-match-snapshot-for-generated-pdf-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-8-snap.png
  forms-shared/tests/tax-form/__snapshots__/taxForm.ts.snap
  forms-shared/tests/tax-form/taxForm.ts
Labels: pr: fix & ship :ship:

#2715 Change ginis file upload to be single threaded
  nest-forms-backend/src/ginis/ginis.service.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2720 Fix: reporting email secrets
  nest-tax-backend/kubernetes/envs/Prod/secrets/email.secret.yml
Labels: pr: needs review :pray:

#2721 Fix Bull V2
  nest-forms-backend/src/app.module.ts
  nest-forms-backend/src/ginis/ginis.module.ts
Labels: pr: fix & ship :ship:

#2722 Form shared update snapshots
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-priznanie-k-dani-z-nehnutelnosti-example-5-no-calculators-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
Labels: pr: fix & ship :ship:

#2723 Revert PDF tax queue
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/app.module.ts
  nest-forms-backend/src/config/ba-config.ts
  nest-forms-backend/src/config/environment-variables.ts
  nest-forms-backend/src/convert/convert.service.spec.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/ginis/ginis.module.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/tax/processor.ts
  nest-forms-backend/src/tax/tax.module.ts
  nest-forms-backend/src/tax/tax.service.ts
  nest-forms-backend/src/tax/worker.ts
Labels: pr: fix & ship :ship:

#2724 Remove inhouse from deploy paths
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:

#2714 Add formId to Slovensko.sk XML
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/signer/signerData.ts
  forms-shared/src/slovensko-sk/extractJson.ts
  forms-shared/src/slovensko-sk/file-templates/schemaXsd.ts
  forms-shared/src/slovensko-sk/generateXml.ts
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
  forms-shared/tests/signer/signerData.ts
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/slovensko-sk/extractJson.ts
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
Labels: pr: fix & ship :ship:

#2726 TSB banners + service cards
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/.env.e2e
  next/assets/icons/environment-construction/lamp.svg
  next/assets/images/banner-stanovisko.png
  next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/environment.ts
  next/frontend/constants/constants.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#2728 Fix ginis document assignment for garden forms
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:
