Repository bratislava/konto.bratislava.sk, pull requests merged in 2025-03, with the labels that each got.

#2348 Update packages 2025 02 27
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-komunitne-zahrady-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-docistenie-stanovista-zbernych-nadob-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-energeticke-zhodnotenie-odpadu-v-zevo-example-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-kolo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-kolo-taxi-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-mimoriadny-odvoz-a-zhodnotenie-odpadu-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-olo-taxi-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-uzatvorenie-zmluvy-o-nakladani-s-odpadom-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-predzahradky-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-1-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-1-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-2-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-2-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-3-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-3-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-3-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-4-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-4-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-priznanie-k-dani-z-nehnutelnosti-example-5-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-8-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-9-snap.png
  nest-forms-backend/.eslintrc.js
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/admin/admin.controller.ts
  nest-forms-backend/src/app.controller.ts
  nest-forms-backend/src/auth/strategies/admin.strategy.ts
  nest-forms-backend/src/auth/strategies/cognito.strategy.ts
  nest-forms-backend/src/convert/convert.controller.ts
  nest-forms-backend/src/files/files.controller.ts
  nest-forms-backend/src/forms/forms.controller.ts
  nest-forms-backend/src/ginis/ginis.controller.ts
  nest-forms-backend/src/nases/nases.controller.ts
  nest-forms-backend/src/signer/signer.controller.ts
  nest-forms-backend/src/status/status.controller.ts
  nest-forms-backend/src/utils/handlers/text.handler.ts
  nest-forms-backend/src/utils/subservices/sharepoint.subservice.ts
  next/components/forms/info-components/FormMarkdown.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/package-lock.json
  next/package.json
Labels: pr: fix & ship :ship:

#2377 97 Komunal prerelease changes
  forms-shared/src/example-forms/examples/oznamenieOPoplatkovejPovinnostiZaKomunalneOdpadyExample.ts
  forms-shared/src/schemas/oznamenieOPoplatkovejPovinnostiZaKomunalneOdpady.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-oznamenie-o-poplatkovej-povinnosti-za-komunalne-odpady-example-summary-pdf-should-match-snapshot-4-snap.png
Labels: pr: fix & ship :ship:

#2315 Add missing information about attachment skip to form support runbook
  docs/runbook/formulare-support.md
Labels: pr: fix & ship :ship:

#2353 791 Integrate shared OpenAPI clients into pipeline
  .github/workflows/build-conditions-konto.yml
  .github/workflows/cypress-test.yaml
  .github/workflows/deploy.yml
  .github/workflows/validate-and-build.yml
  nest-city-account/Dockerfile
  nest-city-account/README.md
  nest-city-account/package-lock.json
  nest-city-account/package.json
  nest-clamav-scanner/Dockerfile
  nest-clamav-scanner/package-lock.json
  nest-clamav-scanner/package.json
  nest-forms-backend/Dockerfile
  nest-forms-backend/README.md
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-tax-backend/Dockerfile
  nest-tax-backend/README.md
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  next/Dockerfile
  next/README.md
  next/package-lock.json
  next/package.json
  openapi-clients/Dockerfile
  openapi-clients/Dockerfile.check
  openapi-clients/city-account/.openapi-generator/VERSION
  openapi-clients/city-account/configuration.ts
  openapi-clients/clamav-scanner/.openapi-generator/VERSION
  openapi-clients/clamav-scanner/configuration.ts
  openapi-clients/forms/.openapi-generator/VERSION
  openapi-clients/forms/configuration.ts
  openapi-clients/openapitools.json
  openapi-clients/package-lock.json
  openapi-clients/package.json
  openapi-clients/scripts/checkForChanges.ts
  openapi-clients/scripts/generateClient.ts
  openapi-clients/slovensko-sk/.openapi-generator/VERSION
  openapi-clients/slovensko-sk/configuration.ts
  openapi-clients/tax/.openapi-generator/VERSION
  openapi-clients/tax/configuration.ts
Labels: pr: needs review :pray:

#2378 Update NestJS and Prisma dependencies only together
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#2397 Update RJSF to 5.24.7
  .github/dependabot.yml
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/src/form-utils/validators.ts
  forms-shared/vitest.config.mts
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  next/package-lock.json
  next/package.json
Labels: pr: fix & ship :ship:

#2275 Configure ClamAV for local development
  clamav/Dockerfile
  clamav/README.md
  clamav/conf/clamd.conf
  clamav/conf/freshclam.conf
  clamav/docker-compose.yml
  clamav/health.sh
  clamav/kubernetes/base/deployment.yml
  clamav/kubernetes/base/kustomization.yml
  clamav/readiness.sh
  clamav/setupconfig.py
  clamav/start.py
  clamav/virus-test-inside.zip
  clamav/virustest
  cvdmirror/Dockerfile
  cvdmirror/README.md
  cvdmirror/docker-compose.yml
  cvdmirror/entrypoint.sh
  cvdmirror/health.sh
  cvdmirror/kubernetes/base/statefulset-cvdmirror.yml
  nest-clamav-scanner/.env.example
  nest-clamav-scanner/.eslintrc.json
  nest-clamav-scanner/Dockerfile
  nest-clamav-scanner/README.md
  nest-clamav-scanner/docker-compose.yml
  nest-clamav-scanner/eslint.config.ts
  nest-clamav-scanner/package-lock.json
  nest-clamav-scanner/package.json
  nest-clamav-scanner/src/app.controller.spec.ts
  nest-clamav-scanner/src/app.controller.ts
  nest-clamav-scanner/src/app.module.ts
  nest-clamav-scanner/src/app.service.ts
  nest-clamav-scanner/src/auth/auth.module.ts
  nest-clamav-scanner/src/auth/strategies/auth-basic.strategy.ts
  nest-clamav-scanner/src/clamav-client/clamav-client.module.ts
  nest-clamav-scanner/src/clamav-client/clamav-client.service.ts
  nest-clamav-scanner/src/common/utils/helpers.ts
  nest-clamav-scanner/src/forms-client/forms-client.module.ts
  nest-clamav-scanner/src/forms-client/forms-client.service.ts
  nest-clamav-scanner/src/main.ts
  nest-clamav-scanner/src/minio-client/minio-client.module.ts
  nest-clamav-scanner/src/minio-client/minio-client.service.ts
  nest-clamav-scanner/src/prisma/prisma.module.ts
  nest-clamav-scanner/src/prisma/prisma.service.ts
  nest-clamav-scanner/src/scanner-cron/scanner-cron.module.ts
  nest-clamav-scanner/src/scanner-cron/scanner-cron.service.ts
  nest-clamav-scanner/src/scanner/scanner.controller.ts
  nest-clamav-scanner/src/scanner/scanner.dto.ts
  nest-clamav-scanner/src/scanner/scanner.module.ts
  nest-clamav-scanner/src/scanner/scanner.service.ts
  nest-clamav-scanner/src/status/status.controller.ts
  nest-clamav-scanner/src/status/status.dto.ts
  nest-clamav-scanner/src/status/status.module.ts
  nest-clamav-scanner/src/status/status.service.ts
  nest-clamav-scanner/tsconfig.json
  nest-clamav-scanner/types/clamdjs.d.ts
  nest-clamav-scanner/types/global.d.ts
  nest-forms-backend/.env.example
  nest-forms-backend/README.md
Labels: pr: fix & ship :ship:

#2425 Fix clamav deploy missing bash to sh
  clamav/kubernetes/base/deployment.yml
Labels: pr: fix & ship :ship:

#2424 Properly hide default labels in RJSF instead of abusing CSS
  forms-shared/src/form-utils/formDefaults.ts
  forms-shared/src/generator/functions/arrayField.ts
  forms-shared/src/generator/functions/checkbox.ts
  forms-shared/src/generator/functions/checkboxGroup.ts
  forms-shared/src/generator/functions/customComponentsField.ts
  forms-shared/src/generator/functions/datePicker.ts
  forms-shared/src/generator/functions/fileUpload.ts
  forms-shared/src/generator/functions/fileUploadMultiple.ts
  forms-shared/src/generator/functions/input.ts
  forms-shared/src/generator/functions/number.ts
  forms-shared/src/generator/functions/radioGroup.ts
  forms-shared/src/generator/functions/select.ts
  forms-shared/src/generator/functions/selectMultiple.ts
  forms-shared/src/generator/functions/textArea.ts
  forms-shared/src/generator/functions/timePicker.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  next/pages/index.css
Labels: pr: fix & ship :ship:

#2429 Hide labels in BaFieldTemplate
  forms-shared/src/form-utils/formDefaults.ts
  forms-shared/src/generator/functions/arrayField.ts
  forms-shared/src/generator/functions/checkbox.ts
  forms-shared/src/generator/functions/checkboxGroup.ts
  forms-shared/src/generator/functions/customComponentsField.ts
  forms-shared/src/generator/functions/datePicker.ts
  forms-shared/src/generator/functions/fileUpload.ts
  forms-shared/src/generator/functions/fileUploadMultiple.ts
  forms-shared/src/generator/functions/input.ts
  forms-shared/src/generator/functions/number.ts
  forms-shared/src/generator/functions/radioGroup.ts
  forms-shared/src/generator/functions/select.ts
  forms-shared/src/generator/functions/selectMultiple.ts
  forms-shared/src/generator/functions/textArea.ts
  forms-shared/src/generator/functions/timePicker.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  next/components/forms/widget-wrappers/BAFieldTemplate.tsx
Labels: pr: fix & ship :ship:

#2442 783 Versioning texts improvements
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#2426 Update ginis-sdk in forms backend
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/__tests__/ginisContants.ts
  nest-forms-backend/src/ginis/dtos/ginis-api.response.dto.ts
  nest-forms-backend/src/ginis/ginis.controller.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.spec.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.ts
  nest-forms-backend/src/ginis/subservices/ginis-tasks.subservice.ts
  nest-forms-backend/src/utils/ginis/ginis-api-helper.ts
  next/clients/openapi-forms/api.ts
  next/clients/openapi-forms/base.ts
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationHistory.tsx
  openapi-clients/forms/api.ts
  openapi-clients/forms/base.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2449 89 Tax campaign
  next/components/forms/segments/AccountSections/IntroSection/Announcements/Announcements.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#2450 774 Tax form email phone optional
  forms-shared/FORMS-CHANGELOG.md
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/priznanie-k-dani-z-nehnutelnosti/osoby.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#2444 Turn on versioning in production
  nest-forms-backend/kubernetes/envs/Prod/.env
  next/.env.bratiska-cli-build.prod
Labels: pr: fix & ship :ship:

#2448 Fix ginis tests in forms backend
  nest-forms-backend/src/ginis/ginis.controller.spec.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.spec.ts
Labels: pr: fix & ship :ship:

#2452 Update OpenAPI clients
  README.md
  openapi-clients/README.md
  openapi-clients/clamav-scanner/api.ts
  openapi-clients/clamav-scanner/client.ts
  openapi-clients/forms/base.ts
  openapi-clients/package.json
  openapi-clients/scripts/generateClient.ts
  openapi-clients/tax/api.ts
Labels: pr: fix & ship :ship:

#2222 Feat: update delivery methods in noris task
  nest-city-account/kubernetes/envs/Dev/.env
  nest-city-account/kubernetes/envs/Prod/.env
  nest-city-account/kubernetes/envs/Staging/.env
  nest-city-account/package-lock.json
  nest-city-account/package.json
  nest-city-account/prisma/migrations/20250203103222_add_year_of_last_update_of_delivery_methods/migration.sql
  nest-city-account/prisma/schema.prisma
  nest-city-account/src/admin/admin.module.ts
  nest-city-account/src/admin/admin.service.ts
  nest-city-account/src/admin/dtos/responses.admin.dto.ts
  nest-city-account/src/admin/utils/account-deactivate.utils.ts
  nest-city-account/src/app.module.ts
  nest-city-account/src/generated-clients/nest-tax-backend/.openapi-generator/FILES
  nest-city-account/src/generated-clients/nest-tax-backend/api.ts
  nest-city-account/src/generated-clients/nest-tax-backend/base.ts
  nest-city-account/src/generated-clients/nest-tax-backend/common.ts
  nest-city-account/src/generated-clients/nest-tax-backend/configuration.ts
  nest-city-account/src/generated-clients/nest-tax-backend/index.ts
  nest-city-account/src/generated-clients/new-magproxy/api.ts
  nest-city-account/src/generated-clients/new-magproxy/base.ts
  nest-city-account/src/generated-clients/new-magproxy/common.ts
  nest-city-account/src/generated-clients/new-magproxy/configuration.ts
  nest-city-account/src/user-verification/utils/subservice/tasks.subservice.ts
  nest-city-account/src/user-verification/verification.module.ts
  nest-city-account/src/user/user.service.ts
  nest-city-account/src/utils/constants/__tests__/tax-deadline.spec.ts
  nest-city-account/src/utils/constants/tax-deadline.ts
  nest-city-account/src/utils/subservices/__tests__/line-logger.subservice.spec.ts
  nest-city-account/src/utils/subservices/__tests__/tasks.subservice.spec.ts
  nest-city-account/src/utils/subservices/tasks.subservice.ts
  nest-city-account/src/utils/subservices/tax.subservice.ts
  nest-city-account/src/utils/types/tax.types.ts
Labels: pr: fix & ship :ship:

#2453 Remove Noris update delivery methods flags and set correct cron
  nest-city-account/kubernetes/envs/Dev/.env
  nest-city-account/kubernetes/envs/Prod/.env
  nest-city-account/kubernetes/envs/Staging/.env
  nest-city-account/src/utils/subservices/__tests__/tasks.subservice.spec.ts
  nest-city-account/src/utils/subservices/tasks.subservice.ts
Labels: pr: fix & ship :ship:

#2451 Fix cypress test
  tests/cypress/e2e/form/formRealEstateTaxReturn.cy.ts
  tests/cypress/support/commands/form.ts
Labels: pr: fix & ship :ship:

#2455 Komunal changes 2025 04 11
  forms-shared/src/generator/functions/conditionalStep.ts
  forms-shared/src/generator/functions/step.ts
  forms-shared/src/generator/uiOptionsTypes.ts
  forms-shared/src/schemas/komunitneZahrady.ts
  forms-shared/src/schemas/oznamenieOPoplatkovejPovinnostiZaKomunalneOdpady.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  next/components/forms/widget-wrappers/BAObjectFieldTemplate.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2456 Change text for biologickyRozlozitelnyOdpadZKuchyne/fyzickaOsoba
  forms-shared/src/schemas/oznamenieOPoplatkovejPovinnostiZaKomunalneOdpady.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#2457 Remove default URL in OpenAPI client
  openapi-clients/scripts/generateClient.ts
Labels: pr: fix & ship :ship:

#2342 Remove storing tax PDFs in debug bucket
  nest-forms-backend/src/convert/convert.service.spec.ts
  nest-forms-backend/src/convert/convert.service.ts
Labels: pr: fix & ship :ship:

#2461 393 TSB form changes
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/tsb/objednavkaInformativnehoZakresuSieti.ts
  forms-shared/src/schemas/tsb/objednavkaVytyceniaPodzemnychVedeniVerejnehoOsvetlenia.ts
  forms-shared/src/schemas/tsb/objednavkaZakresuSieti.ts
  forms-shared/src/schemas/tsb/shared/getObjednavatelZiadatelStep.ts
  forms-shared/src/schemas/tsb/umiestnenieZariadenia.ts
  forms-shared/src/schemas/tsb/ziadostOStanoviskoKProjektovejDokumentacii.ts
  forms-shared/src/schemas/tsb/ziadostOStanoviskoPD.ts
  forms-shared/src/schemas/tsb/ziadostOUmiestnenieInehoZariadeniaNaStoziarVerejnehoOsvetlenia.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#2479 fix: add configModule to admin dependencies
  nest-city-account/src/admin/admin.module.ts
  nest-city-account/src/app.module.ts
  nest-clamav-scanner/src/auth/auth.module.ts
  nest-forms-backend/src/auth/auth.module.ts
  nest-forms-backend/src/files/files.module.ts
Labels: pr: fix & ship :ship:

#2480 Minor cleanup in strapi configs
  docker-compose.yml
  strapi/.gitignore
  strapi/config/middlewares.ts
  strapi/config/server.ts
Labels: pr: fix & ship :ship:

#2454 add KontaktovanyEmailom field to main Sharepoint card
  forms-shared/src/example-forms/examples/ziadostONajomBytuExample.ts
  forms-shared/src/sharepoint/mappings/ziadostONajomBytu.ts
  forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap
Labels: pr: fix & ship :ship:

#2351 send TSB forms by Email
  forms-shared/src/definitions/emailFormTypes.ts
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/schemas/tsb/objednavkaInformativnehoZakresuSieti.ts
  forms-shared/src/schemas/tsb/objednavkaVytyceniaPodzemnychVedeniVerejnehoOsvetlenia.ts
  forms-shared/src/schemas/tsb/ziadostOStanoviskoKProjektovejDokumentacii.ts
  forms-shared/src/schemas/tsb/ziadostOUmiestnenieInehoZariadeniaNaStoziarVerejnehoOsvetlenia.ts
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/ginis/ginis.module.ts
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.module.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.spec.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/dtos/email-forms.errors.enum.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/utils/global-dtos/mailgun.dto.ts
  nest-forms-backend/src/utils/global-services/mailer/mailer.interface.ts
  nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts
  nest-forms-backend/src/utils/global-services/mailer/mailgun.service.ts
  nest-forms-backend/src/utils/global-services/mailer/olo-mailer.service.ts
  nest-forms-backend/src/utils/global-services/mailer/utils/mailgun.helper.spec.ts
  nest-forms-backend/src/utils/global-services/mailer/utils/mailgun.helper.ts
  nest-forms-backend/src/utils/global-services/mailgun/mailgun.service.ts
  nest-forms-backend/src/utils/types/prisma.ts
Labels: pr: fix & ship :ship:

#2482 97 Release Oznámenie o poplatkovej povinnosti za komunálne odpady
  nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts
  next/.env.bratiska-cli-build.prod
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/frontend/constants/constants.tsx
Labels: pr: fix & ship :ship:

#2483 393 TSB form changes 2025-03-20
  forms-shared/src/schemas/tsb/objednavkaVytyceniaPodzemnychVedeniVerejnehoOsvetlenia.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#2484 [bratislava/private-konto.bratislava.sk#767]set correct tsb mailgun t…
  nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts
Labels: pr: fix & ship :ship:

#2481 Move feedback links to form definitions
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts
  next/clients/graphql-strapi/api.ts
  next/clients/graphql-strapi/queries/Tax.graphql
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouSection.tsx
  next/components/forms/segments/TaxFormPdfExportModal/TaxFormPdfExportModal.tsx
  next/frontend/constants/constants.tsx
  strapi/schema.graphql
  strapi/src/api/tax/content-types/tax/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#2489 Next update packages 2025-03-23
  next/package-lock.json
  next/package.json
Labels: pr: fix & ship :ship:

#2491 Remove Next old API clients
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesDeliveryMethodCard.tsx
  next/frontend/api/api.ts
  next/frontend/dtos/generalApiDto.ts
  next/frontend/hooks/useEnum.ts
  next/pages/overenie-identity.tsx
  next/pages/zmena-emailu.tsx
  openapi-clients/city-account/api.ts
  openapi-clients/city-account/client.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2492 736 Úpravy žiadosti o stanovisko k investičnému zámeru
  forms-shared/FORMS-CHANGELOG.md
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/example-forms/examples/stanoviskoKInvesticnemuZameruExample.ts
  forms-shared/src/schemas/sekcia-uzemneho-rozvoja/surSchemas.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-1-snap.png
  tests/cypress/e2e/form/formSIZ.cy.ts
Labels: pr: fix & ship :ship:

#2490 Use JSON endpoint to fetch Slovensko.sk metadata
  forms-shared/Dockerfile
  forms-shared/test-utils/fetchSlovenskoSkFormMetadata.ts
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
Labels: pr: fix & ship :ship:

#2519 Fix/tsb forms email subjects
  forms-shared/src/definitions/emailFormTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts
Labels: pr: fix & ship :ship:

#2520 Komunal change text
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#2521 Change ginis endpoints to https
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
Labels: pr: fix & ship :ship:

#2523 Feat: add feedback links to tsb mails
  forms-shared/src/definitions/formDefinitions.ts
  nest-forms-backend/src/utils/global-services/mailer/mailgun.constants.ts
Labels: pr: fix & ship :ship:

#2486 846 Forms send policy
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/send-policy/sendPolicy.ts
  forms-shared/tests/send-policy/sendPolicy.ts
  nest-forms-backend/src/forms/forms.helper.spec.ts
  nest-forms-backend/src/forms/forms.helper.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases/nases.controller.ts
  nest-forms-backend/src/nases/nases.errors.dto.ts
  nest-forms-backend/src/nases/nases.errors.enum.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
  nest-forms-backend/src/nases/nases.service.ts
  nest-forms-backend/src/nases/utils-services/user-to-send-policy-account-type.spec.ts
  nest-forms-backend/src/nases/utils-services/user-to-send-policy-account-type.ts
  next/components/forms/segments/RegistrationModal/RegistrationModal.tsx
  next/components/forms/steps/Summary/SummaryFormControls.tsx
  next/components/forms/useFormContext.tsx
  next/components/forms/useFormModals.tsx
  next/components/forms/useFormSend.tsx
  next/public/locales/sk/forms.json
  tests/cypress/e2e/form/formRealEstateTaxReturn.cy.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2525 798 Fix Nest Forms BE validated config
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/src/config/ba-config.ts
  nest-forms-backend/src/config/environment-variables.ts
  nest-forms-backend/src/main.ts
Labels: pr: fix & ship :ship:

#2524 Fix ginis state checks for user forms
  nest-forms-backend/src/ginis/subservices/ginis-tasks.subservice.ts
Labels: pr: fix & ship :ship:

#2527 393 TSB form changes 2025 03 26
  forms-shared/src/schemas/tsb/shared/getObjednavatelZiadatelStep.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#2531 Remove gestor from form definition
  forms-shared/src/definitions/devFormDefinitions.ts
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/slovensko-sk/file-templates/metaXml.ts
  forms-shared/tests/slovensko-sk/slovenskoSkForm.ts
  nest-forms-backend/src/nases/nases.service.spec.ts
Labels: pr: fix & ship :ship:

#2529 Regenerate OpenAPI clients 2025-03-26
  openapi-clients/forms/api.ts
Labels: pr: fix & ship :ship:

#2528 Remove Bloomreach from Forms BE env variables
  nest-forms-backend/.env.example
  nest-forms-backend/src/config/ba-config.ts
  nest-forms-backend/src/config/environment-variables.ts
Labels: pr: fix & ship :ship:

#2533 Improve test performance
  forms-shared/tests/form-utils/fastMergeAllOfComparision.tsx
Labels: pr: fix & ship :ship:

#2535 Display "Späť na Moje žiadosti" only when signed in
  next/components/forms/FormVersionCompareAction.tsx
Labels: pr: fix & ship :ship:

#2518 #849 - import delivery method with tax
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  nest-tax-backend/prisma/migrations/20250325103255_add_delivery_method_to_tax/migration.sql
  nest-tax-backend/prisma/migrations/migration_lock.toml
  nest-tax-backend/prisma/schema.prisma
  nest-tax-backend/src/admin/admin.service.ts
  nest-tax-backend/src/bloomreach/bloomreach.dto.ts
  nest-tax-backend/src/noris/noris.dto.ts
  nest-tax-backend/src/noris/noris.queries.ts
  nest-tax-backend/src/tax/dtos/requests.tax.dto.ts
  nest-tax-backend/src/utils/types/types.prisma.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2538 react-email-dependencies group in dependabot
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#2537 SUR form changes
  forms-shared/FORMS-CHANGELOG.md
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/example-forms/examples/stanoviskoKInvesticnemuZameruExample.ts
  forms-shared/src/example-forms/examples/zavazneStanoviskoKInvesticnejCinnostiExample.ts
  forms-shared/src/schemas/stanoviskoKInvesticnemuZameru.ts
  forms-shared/src/schemas/zavazneStanoviskoKInvesticnejCinnosti.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-3-snap.png
  tests/cypress/e2e/form/formSIZ.cy.ts
Labels: pr: fix & ship :ship:

#2563 #95 #785 #843 OLO form changes
  forms-shared/FORMS-CHANGELOG.md
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/example-forms/examples/oloPodnetyAPochvalyObcanovExample.ts
  forms-shared/src/example-forms/examples/oloTriedenyZberPapieraPlastovASklaPrePravnickeOsobyExample.ts
  forms-shared/src/example-forms/examples/oloTriedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnostiExample.ts
  forms-shared/src/schemas/olo/oloTaxi.ts
  forms-shared/src/schemas/olo/podnetyAPochvalyObcanov.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPrePravnickeOsoby.ts
  forms-shared/src/schemas/olo/triedenyZberPapieraPlastovASklaPreSpravcovskeSpolocnosti.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-podnety-a-pochvaly-obcanov-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-podnety-a-pochvaly-obcanov-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-podnety-a-pochvaly-obcanov-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-pravnicke-osoby-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-olo-triedeny-zber-papiera-plastov-a-skla-pre-spravcovske-spolocnosti-example-summary-pdf-should-match-snapshot-2-snap.png
Labels: pr: fix & ship :ship:

#2564 Set dependabot to run on sundays
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#2577 735 736 SUR forms changes v2
  forms-shared/src/example-forms/examples/stanoviskoKInvesticnemuZameruExample.ts
  forms-shared/src/example-forms/examples/zavazneStanoviskoKInvesticnejCinnostiExample.ts
  forms-shared/src/schemas/stanoviskoKInvesticnemuZameru.ts
  forms-shared/src/schemas/zavazneStanoviskoKInvesticnejCinnosti.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-stanovisko-k-investicnemu-zameru-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-zavazne-stanovisko-k-investicnej-cinnosti-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-zavazne-stanovisko-k-investicnej-cinnosti-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-zavazne-stanovisko-k-investicnej-cinnosti-example-pdf-should-match-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-zavazne-stanovisko-k-investicnej-cinnosti-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-zavazne-stanovisko-k-investicnej-cinnosti-example-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-stanovisko-k-investicnemu-zameru-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-stanovisko-k-investicnemu-zameru-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-zavazne-stanovisko-k-investicnej-cinnosti-example-summary-pdf-should-match-snapshot-3-snap.png
  tests/cypress/e2e/form/formRegistrationRedirect-mobile.cy.ts
  tests/cypress/e2e/form/formRegistrationRedirect.cy.ts
  tests/cypress/e2e/form/formSIZ.cy.ts
  tests/cypress/e2e/form/formSummaryCheck.cy.ts
  tests/cypress/e2e/form/formZSIZ.cy.ts
  tests/cypress/fixtures/formSummaryCheck.json
Labels: pr: fix & ship :ship:
