Repository bratislava/konto.bratislava.sk, pull requests merged in 2025-05, with the labels that each got.

#2730 #104 Allow guest identities on client
  nest-forms-backend/src/main.ts
  next/clients/axios-instance.ts
  next/components/forms/FormLandingPage.tsx
  next/components/forms/FormVersionCompareAction.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationDetailsHeader.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsCard.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsList.tsx
  next/components/forms/segments/AccountSections/MyApplicationsSection/MyApplicationsSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/useTaxFeeSection.tsx
  next/components/forms/signer/useFormSignature.tsx
  next/components/forms/useFormFileUpload.tsx
  next/components/forms/useFormRedirects.tsx
  next/components/forms/useFormSend.tsx
  next/frontend/hooks/useFormExportImport.tsx
  next/frontend/hooks/useQueryParamRedirect.ts
  next/frontend/hooks/useUser.ts
  next/frontend/utils/amplifyClient.ts
  next/frontend/utils/amplifyConfig.ts
  next/frontend/utils/amplifyServer.ts
  next/frontend/utils/formFileUpload.ts
  next/frontend/utils/queryParamRedirect.ts
  next/pages/dane-a-poplatky/[year].tsx
  next/pages/dane-a-poplatky/index.tsx
  next/pages/get-jwt.tsx
  next/pages/mestske-sluzby/[slug]/[id].tsx
  next/pages/mestske-sluzby/[slug]/index.tsx
  next/pages/moj-profil.tsx
  next/pages/moje-ziadosti/[ziadost].tsx
  next/pages/moje-ziadosti/index.tsx
  next/pages/overenie-identity.tsx
  next/pages/sso.tsx
  next/pages/zmena-emailu.tsx
Labels: pr: fix & ship :ship:

#2717 Use openapi-clients in tax backend
  nest-city-account/Dockerfile
  nest-tax-backend/Dockerfile
  nest-tax-backend/openapitools.json
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  nest-tax-backend/src/admin/admin.module.ts
  nest-tax-backend/src/auth/decorators/user-info-pipe.module.ts
  nest-tax-backend/src/auth/decorators/user-info.decorator.ts
  nest-tax-backend/src/auth/guards/cognito.guard.ts
  nest-tax-backend/src/clients/clients.module.ts
  nest-tax-backend/src/clients/clients.service.ts
  nest-tax-backend/src/generated-clients/nest-city-account/.npmignore
  nest-tax-backend/src/generated-clients/nest-city-account/.openapi-generator-ignore
  nest-tax-backend/src/generated-clients/nest-city-account/.openapi-generator/FILES
  nest-tax-backend/src/generated-clients/nest-city-account/.openapi-generator/VERSION
  nest-tax-backend/src/generated-clients/nest-city-account/api.ts
  nest-tax-backend/src/generated-clients/nest-city-account/base.ts
  nest-tax-backend/src/generated-clients/nest-city-account/common.ts
  nest-tax-backend/src/generated-clients/nest-city-account/configuration.ts
  nest-tax-backend/src/generated-clients/nest-city-account/git_push.sh
  nest-tax-backend/src/generated-clients/nest-city-account/index.ts
  nest-tax-backend/src/payment/payment.controller.ts
  nest-tax-backend/src/payment/payment.module.ts
  nest-tax-backend/src/tax/tax.controller.ts
  nest-tax-backend/src/tax/tax.module.ts
  nest-tax-backend/src/utils/filters/error.filter.ts
  nest-tax-backend/src/utils/global-dtos/city-account.dto.ts
  nest-tax-backend/src/utils/guards/dtos/error.dto.ts
  nest-tax-backend/src/utils/logging.ts
  nest-tax-backend/src/utils/subservices/cityaccount.subservice.ts
Labels: pr: fix & ship :ship:

#2757 Replace tax PDF generation with worker
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/convert/convert.service.spec.ts
  nest-forms-backend/src/convert/convert.service.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/tax/tax.service.ts
  nest-forms-backend/src/tax/worker.ts
Labels: pr: fix & ship :ship:

#2732 833 Replace ginis automation register functionality with ginis api
  nest-forms-backend/.env.example
  nest-forms-backend/kubernetes/envs/Dev/.env
  nest-forms-backend/kubernetes/envs/Prod/.env
  nest-forms-backend/kubernetes/envs/Staging/.env
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/config/ba-config.ts
  nest-forms-backend/src/config/environment-variables.ts
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.spec.ts
  nest-forms-backend/src/ginis/subservices/ginis-api.service.ts
Labels: pr: fix & ship :ship:

#2760 Temporary higher connection limit in tax backend
  nest-tax-backend/kubernetes/base/kustomization.yml
Labels: pr: fix & ship :ship:

#2762 Lower batch to 100 for importing of taxes
  nest-city-account/src/utils/subservices/tasks.subservice.ts
Labels: pr: fix & ship :ship:

#2766 Temporary higher connection limit in city-account
  nest-city-account/kubernetes/base/deployment.yml
  nest-tax-backend/kubernetes/base/kustomization.yml
Labels: pr: fix & ship :ship:

#2767 Increase CPU and RAM resources for account and tax
  nest-city-account/kubernetes/envs/Prod/config.json
  nest-tax-backend/kubernetes/envs/Prod/config.json
Labels: pr: fix & ship :ship:

#2769 Disable guest access
  next/clients/axios-instance.ts
  next/frontend/utils/amplifyConfig.ts
Labels: pr: fix & ship :ship:

#2770 add statusBarContent
  next/public/locales/sk/common.json
Labels: pr: fix & ship :ship:

#2759 Add endpoint for generating reports
  nest-tax-backend/src/admin/dtos/requests.dto.ts
  nest-tax-backend/src/card-payment-reporting/__tests__/card-payment-reporting.service.spec.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.controller.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.module.ts
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.service.ts
  nest-tax-backend/src/tasks/__tests__/tasks.service.spec.ts
  nest-tax-backend/src/tasks/tasks.module.ts
  nest-tax-backend/src/tasks/tasks.service.ts
  nest-tax-backend/src/utils/subservices/__tests__/sftp-file.subservice.spec.ts
  nest-tax-backend/src/utils/subservices/database.subservice.ts
  nest-tax-backend/src/utils/subservices/sftp-file.subservice.ts
Labels: pr: fix & ship :ship:

#2773 Fix: remove leading zeroes from orderId
  nest-tax-backend/src/card-payment-reporting/card-payment-reporting.service.ts
Labels: pr: fix & ship :ship:

#2772 668 787 786 Najomne byvanie changes
  forms-shared/FORMS-CHANGELOG.md
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/example-forms/examples/ziadostONajomBytuExample.ts
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/src/sharepoint/mappings/ziadostONajomBytu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
  forms-shared/tests/sharepoint/__snapshots__/getValuesForSharepoint.ts.snap
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-html-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-html-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/slovensko-sk/__image_snapshots__/slovensko-sk-form-ts-slovensko-sk-form-ziadost-o-najom-bytu-example-pdf-should-match-snapshot-7-snap.png
  forms-shared/tests/slovensko-sk/__snapshots__/slovenskoSkForm.ts.snap
  forms-shared/tests/string-templates/__snapshots__/renderTemplate.ts.snap
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najom-bytu-example-summary-email-should-match-desktop-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-email/__image_snapshots__/render-summary-email-ts-render-summary-email-ziadost-o-najom-bytu-example-summary-email-should-match-mobile-screenshot-snapshot-1-snap.png
  forms-shared/tests/summary-json/__snapshots__/getSummaryJson.ts.snap
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-2-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-3-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-4-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-5-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-6-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-7-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-8-snap.png
  forms-shared/tests/summary-pdf/__image_snapshots__/render-summary-pdf-ts-get-summary-json-ziadost-o-najom-bytu-example-summary-pdf-should-match-snapshot-9-snap.png
Labels: pr: fix & ship :ship:

#2761 845 Use .xdcf extension in form signer
  forms-shared/src/signer/signerData.ts
  forms-shared/tests/signer/__snapshots__/signerData.ts.snap
Labels: pr: fix & ship :ship:

#2800 Najomne byvanie change text 2025 05 12
  forms-shared/src/schemas/ziadostONajomBytu.ts
  forms-shared/tests/definitions/__snapshots__/formDefinitions.ts.snap
Labels: pr: fix & ship :ship:

#2803 Add feedback link
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#2763 use findMany instead of findFirst when possible
  nest-tax-backend/src/admin/admin.service.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2804 Fix reporting variable symbols pairing test
  nest-tax-backend/src/card-payment-reporting/__tests__/card-payment-reporting.service.spec.ts
Labels: pr: fix & ship :ship:

#2685 Send event to bloomreach for unpaid tax notification
  nest-tax-backend/.env.example
  nest-tax-backend/kubernetes/envs/Dev/.env
  nest-tax-backend/kubernetes/envs/Prod/.env
  nest-tax-backend/kubernetes/envs/Staging/.env
  nest-tax-backend/prisma/migrations/20250425133953_add_field_for_bloomreach_unpaid_tax_reminder/migration.sql
  nest-tax-backend/prisma/migrations/migration_lock.toml
  nest-tax-backend/prisma/schema.prisma
  nest-tax-backend/src/bloomreach/bloomreach.dto.ts
  nest-tax-backend/src/bloomreach/bloomreach.service.ts
  nest-tax-backend/src/tasks/__tests__/tasks.service.spec.ts
  nest-tax-backend/src/tasks/tasks.module.ts
  nest-tax-backend/src/tasks/tasks.service.ts
  nest-tax-backend/src/tax/dtos/requests.tax.dto.ts
Labels: pr: fix & ship :ship:

#2805 Fix tax BE build
  nest-tax-backend/src/tasks/tasks.module.ts
Labels: pr: fix & ship :ship:

#2806 Forms shared tests docker
  forms-shared/Dockerfile
  forms-shared/README.md
  forms-shared/package.json
  forms-shared/scripts/runDockerTest.ts
Labels: pr: fix & ship :ship:

#2807 E2E tests setup for Forms BE
  .github/workflows/validate-and-build.yml
  .github/workflows/validate-nest-prisma-konto.yml
  nest-forms-backend/jest.e2e-config.ts
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-forms-backend/src/app.e2e-spec.ts
  nest-forms-backend/test/e2e-global-setup.ts
  nest-forms-backend/test/e2e-global-shared.ts
  nest-forms-backend/test/e2e-global-teardown.ts
Labels: pr: fix & ship :ship:

#2584 795 Use openapi-clients in virus scanner
  nest-city-account/package-lock.json
  nest-city-account/package.json
  nest-clamav-scanner/.prettierrc
  nest-clamav-scanner/Dockerfile
  nest-clamav-scanner/docker-compose.yml
  nest-clamav-scanner/package-lock.json
  nest-clamav-scanner/package.json
  nest-clamav-scanner/src/app.controller.spec.ts
  nest-clamav-scanner/src/app.controller.ts
  nest-clamav-scanner/src/app.module.ts
  nest-clamav-scanner/src/app.service.ts
  nest-clamav-scanner/src/auth/auth.controller.ts
  nest-clamav-scanner/src/auth/auth.module.ts
  nest-clamav-scanner/src/auth/auth.service.ts
  nest-clamav-scanner/src/auth/guards/auth-basic.guard.ts
  nest-clamav-scanner/src/auth/strategies/auth-basic.strategy.ts
  nest-clamav-scanner/src/clamav-client/clamav-client.module.ts
  nest-clamav-scanner/src/clamav-client/clamav-client.service.ts
  nest-clamav-scanner/src/clients/clients.module.ts
  nest-clamav-scanner/src/clients/clients.service.ts
  nest-clamav-scanner/src/common/utils/helpers.ts
  nest-clamav-scanner/src/forms-client/forms-client.module.ts
  nest-clamav-scanner/src/forms-client/forms-client.service.ts
  nest-clamav-scanner/src/main.ts
  nest-clamav-scanner/src/minio-client/minio-client.module.ts
  nest-clamav-scanner/src/minio-client/minio-client.service.ts
  nest-clamav-scanner/src/prisma/prisma.module.ts
  nest-clamav-scanner/src/prisma/prisma.service.ts
  nest-clamav-scanner/src/scanner-cron/scanner-cron.dto.ts
  nest-clamav-scanner/src/scanner-cron/scanner-cron.module.ts
  nest-clamav-scanner/src/scanner-cron/scanner-cron.service.ts
  nest-clamav-scanner/src/scanner/scanner.controller.ts
  nest-clamav-scanner/src/scanner/scanner.dto.ts
  nest-clamav-scanner/src/scanner/scanner.module.ts
  nest-clamav-scanner/src/scanner/scanner.service.ts
  nest-clamav-scanner/src/status/status.controller.ts
  nest-clamav-scanner/src/status/status.dto.ts
  nest-clamav-scanner/src/status/status.module.ts
  nest-clamav-scanner/src/status/status.service.ts
  nest-forms-backend/package-lock.json
  nest-forms-backend/package.json
  nest-tax-backend/package-lock.json
  nest-tax-backend/package.json
  next/package-lock.json
  next/package.json
  openapi-clients/package-lock.json
  openapi-clients/package.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#2764 836 Use proper message subject in messages going to ginis
  forms-shared/README.md
  forms-shared/src/definitions/formDefinitionTypes.ts
  forms-shared/src/definitions/formDefinitions.ts
  forms-shared/src/form-utils/formDataExtractors.ts
  forms-shared/src/schemas/komunitneZahrady.ts
  forms-shared/src/schemas/predzahradky.ts
  forms-shared/src/schemas/priznanieKDaniZNehnutelnosti.ts
  forms-shared/src/schemas/stanoviskoKInvesticnemuZameru.ts
  forms-shared/src/schemas/zavazneStanoviskoKInvesticnejCinnosti.ts
  forms-shared/tests/form-utils/__snapshots__/formDataExtractors.ts.snap
  forms-shared/tests/form-utils/formDataExtractors.ts
  nest-forms-backend/src/forms/forms.service.ts
  nest-forms-backend/src/ginis/ginis.service.spec.ts
  nest-forms-backend/src/ginis/ginis.service.ts
  nest-forms-backend/src/nases-consumer/nases-consumer.service.ts
  nest-forms-backend/src/nases-consumer/subservices/__test__/email-forms.subservice.spec.ts
  nest-forms-backend/src/nases-consumer/subservices/email-forms.subservice.ts
  nest-forms-backend/src/nases/nases.service.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.spec.ts
  nest-forms-backend/src/nases/utils-services/tokens.nases.service.ts
  nest-forms-backend/src/utils/subservices/__test__/sharepoint.subservice.spec.ts
  nest-forms-backend/src/utils/subservices/sharepoint.subservice.ts
Labels: pr: fix & ship :ship:

#2832 remove FEATURE_TOGGLE_REMINDER_UNPAID_TAX flag
  nest-tax-backend/.env.example
  nest-tax-backend/kubernetes/envs/Dev/.env
  nest-tax-backend/kubernetes/envs/Prod/.env
  nest-tax-backend/kubernetes/envs/Staging/.env
  nest-tax-backend/src/tasks/__tests__/tasks.service.spec.ts
  nest-tax-backend/src/tasks/tasks.service.ts
Labels: pr: fix & ship :ship:

#2833 Fix api type in city-account endpoint
  nest-city-account/src/admin/admin.controller.ts
  nest-city-account/src/admin/dtos/requests.admin.dto.ts
Labels: pr: fix & ship :ship:

#2835 Add missing throw in OloMailer
  nest-forms-backend/src/utils/global-services/mailer/olo-mailer.service.ts
Labels: pr: fix & ship :ship:

#2837 Revert "add statusBarContent (#2770)"
  next/public/locales/sk/common.json
Labels: pr: needs review :pray:

#2839 877 TSB bump version update changelog
  forms-shared/FORMS-CHANGELOG.md
  forms-shared/src/definitions/formDefinitions.ts
Labels: pr: fix & ship :ship:

#2841 Revert logging and formatting improvements
  nest-city-account/src/user-verification/utils/subservice/verification.subservice.ts
  nest-city-account/src/user-verification/verification.controller.ts
  nest-city-account/src/user-verification/verification.service.ts
  nest-city-account/src/utils/subservices/line-logger.subservice.ts
Labels: pr: needs review :pray:

#2856 Update packages 2025 05 27
  forms-shared/package-lock.json
  forms-shared/package.json
  forms-shared/src/generated-assets/summaryPdfCss.ts
  nest-forms-backend/package-lock.json
  next/package-lock.json
  next/package.json
  openapi-clients/package-lock.json
  openapi-clients/package.json
Labels: pr: fix & ship :ship:

#2870 Fix CognitoUserService
  nest-forms-backend/src/auth-v2/services/cognito-user.service.ts
Labels: pr: fix & ship :ship:

#2873 Fix CognitoUserService V3
  nest-forms-backend/src/auth-v2/services/cognito-user.service.ts
Labels: pr: fix & ship :ship:
